export enum PlayerLogTypes {
  // Generic logs
  switchToMP4 = 'switchToMP4',
  retryLoad = 'retryLoad',
  skip = 'skip',

  // MP4 Player logs
  mp4Init = 'MP4Init',
  mp4Abort = 'MP4Abort',
  mp4CanPlay = 'MP4CanPlay',
  mp4CanPlayThrough = 'MP4CanPlayThrough',
  mp4DurationChange = 'MP4DurationChange',
  mp4Emptied = 'MP4Emptied',
  mp4Ended = 'MP4Ended',
  mp4Error = 'MP4Error',
  mp4LoadedData = 'MP4LoadedData',
  mp4LoadedMetaData = 'MP4LoadedMetaData',
  mp4LoadStart = 'MP4LoadStart',
  mp4Pause = 'MP4Pause',
  mp4Play = 'MP4Play',
  mp4Playing = 'MP4Playing',
  mp4Progress = 'MP4Progress',
  mp4RateChange = 'MP4RateChange',
  mp4Seeked = 'MP4Seeked',
  mp4Seeking = 'MP4Seeking',
  mp4Stalled = 'MP4Stalled',
  mp4Suspend = 'MP4Suspend',
  mp4VolumeChange = 'MP4VolumeChange',
  mp4Waiting = 'MP4Waiting',

  // Dash player logs
  dashLoadError = 'dashLoadError',
  dashInit = 'dashInit',
  dashFragmentLoaded = 'dashFragmentLoaded',
  dashBuffering = 'dashBuffering',
  dashError = 'dashError',
  dashSetupError = 'dashSetupError',
  dashManifestParsed = 'dashManifestParsed',
  dashMediaQualityChanged = 'dashMediaQualityChanged',
  dashGapJumped = 'dashGapJumped',
  dashStallDetected = 'dashStallDetected',
  dashStreamingError = 'dashStreamingError',
  dashStreamingErrorMax = 'dashStreamingErrorMax',
  dashPlaybackError = 'dashPlaybackError',
  dashPlaybackErrorMax = 'dashPlaybackErrorMax',

  // HLS Shaka player logs
  hlsShakaLoadError = 'hlsShakaLoadError',
  hlsShakaInit = 'hlsShakaInit',
  hlsShakaFragmentLoaded = 'hlsShakaFragmentLoaded',
  hlsShakaBuffering = 'hlsShakaBuffering',
  hlsShakaSetupError = 'hlsShakaSetupError',
  hlsShakaManifestParsed = 'hlsShakaManifestParsed',
  hlsShakaMediaQualityChanged = 'hlsShakaMediaQualityChanged',
  hlsShakaGapJumped = 'hlsShakaGapJumped',
  hlsShakaStallDetected = 'hlsShakaStallDetected',
  hlsShakaStreamingError = 'hlsShakaStreamingError',
  hlsShakaStreamingErrorMax = 'hlsShakaStreamingErrorMax',
  hlsShakaPlaybackError = 'hlsShakaPlaybackError',
  hlsShakaPlaybackErrorMax = 'hlsShakaPlaybackErrorMax',

  // HLS player logs
  hlsConfiguration = 'hlsConfiguration',
  hlsMediaAttached = 'hlsMediaAttached',
  hlsMediaDetached = 'hlsMediaDetached',
  hlsBufferReset = 'hlsBufferReset',
  hlsBufferCreated = 'hlsBufferCreated',
  hlsBufferAppended = 'hlsBufferAppended',
  hlsBufferEos = 'hlsBufferEos',
  hlsBufferFlushed = 'hlsBufferFlushed',
  hlsManifestParsed = 'hlsManifestParsed',
  hlsLevelSwitched = 'hlsLevelSwitched',
  hlsLevelLoaded = 'hlsLevelLoaded',
  hlsAudioTrackSwitched = 'hlsAudioTrackSwitched',
  hlsFragLoadEmergencyAborted = 'hlsFragLoadEmergencyAborted',
  hlsFragBuffered = 'hlsFragBuffered',
  hlsFpsDrop = 'hlsFpsDrop',
  hlsFpsDropLevelCapping = 'hlsFpsDropLevelCapping',
  hlsDestroying = 'hlsDestroying',
  hlsFragChanged = 'hlsFragChanged',
  hlsFragLoading = 'hlsFragLoading',
  hlsFragLoaded = 'hlsFragLoaded',
  hlsError = 'hlsError',
  hlsSetupError = 'hlsSetupError',
}
