/* eslint-disable no-console */
import { useVideoPasswordContext } from '@js/common/video-password';

import {
  Video,
  VideoModel,
  useVideoContext,
} from '@js/common/video-player/context';
import React, { useCallback, useEffect, useRef, useState } from 'react';
// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import { reactLazyRetry } from '@js/utilities/reactLazyRetry';

import { IngestionType } from '@loomhq/shared-utilities/constants/ingestionType';

import { useErrorStore } from '../../../../components/video-player-fresh/error-layer/ErrorStoreProvider';
import FetchVideoData from '../../../../components/video-player-fresh/hooks/FetchVideoData.gql';
import {
  parseGraphQLVideo,
  shouldWaitForTranscodeComplete,
} from '../../../../components/video-player-fresh/utils';

import {
  useVideoUploadProgressUpdatedSubscription,
  VideoUploadProgressUpdatedSubscription,
} from './VideoUploadProgressSubscription.generated';

import * as logger from '@js/utilities/loggerx';
import { Feature } from '@loomhq/shared-utilities/constants/product';

const LazyProgressLayer = reactLazyRetry(() =>
  import(/* webpackChunkName: "ProgressLayer" */ './ProgressLayer').then(
    module => ({ default: module.ProgressLayer })
  )
);

const LazyZoomIngestionModal = reactLazyRetry(() =>
  import(
    /* webpackChunkName: "ZoomIngestionModal" */ './ZoomIngestionModal'
  ).then(module => ({ default: module.ZoomIngestionModal }))
);

export const LazyUploadProgress: React.FC<
  React.PropsWithChildren<unknown>
> = () => {
  return (
    <React.Suspense fallback={null}>
      <UploadProgress />
    </React.Suspense>
  );
};

const LOADING_ANIMATION_COMPLETE_TIMEOUT = 1000;
const VIDEO_UPLOAD_ERROR = 'Video upload error';

// Use to wait for progress bar complete animation to finish before showing play button
const waitForLoadingAnimation = () =>
  new Promise(resolve =>
    setTimeout(resolve, LOADING_ANIMATION_COMPLETE_TIMEOUT)
  );

const useLoadingProgressHook = ({ setProgressValue, setIsComplete }) => {
  const videoRef = useRef<Video>();

  const { video, setVideo } = useVideoContext();
  const { password, setNeedsPassword } = useVideoPasswordContext();
  const { pushError } = useErrorStore();

  const waitForTranscodeComplete = shouldWaitForTranscodeComplete(
    videoRef.current?.videoProperties?.mediaMetadataRotation
  );

  // Since we are modifying video context in provider, need to save to ref to avoid rerender loop
  useEffect(() => {
    videoRef.current = video;
  }, [video]);

  const onUploadDone = useCallback(async () => {
    setProgressValue(100);
    setIsComplete(true);

    await waitForLoadingAnimation();

    // Create final GQL call after upload is complete to load full video model and show play button
    const gqlClient = getGraphQLClient();

    gqlClient
      .query({
        query: FetchVideoData,
        variables: { id: videoRef.current?.modelId, password },
        fetchPolicy: 'no-cache',
      })
      .then(({ data }) => {
        setVideo({
          ...parseGraphQLVideo(data.video),
          isMainVideoOnPage: video.isMainVideoOnPage,
        } as VideoModel);
        setNeedsPassword(data.video.needs_password);
      });
  }, [
    setNeedsPassword,
    setProgressValue,
    setIsComplete,
    password,
    setVideo,
    video.isMainVideoOnPage,
  ]);

  const onProgress = useCallback(
    (nextProgressValue: number) => {
      setProgressValue(prevProgressValue => {
        const latestProgress = Math.max(prevProgressValue, nextProgressValue);

        return latestProgress;
      });
    },
    [setProgressValue]
  );

  const handleSubscriptionData = useCallback(
    (data: VideoUploadProgressUpdatedSubscription) => {
      const message = data?.videoUploadProgressUpdated;

      if (!message) {
        return;
      }

      // TODO: revisit notification UX and visibility / privacy logic
      if (message.videoUploadValid === false) {
        pushError(VIDEO_UPLOAD_ERROR);

        const processingInformation =
          videoRef.current?.processingInformation || {};

        const nextVideoObj = {
          ...videoRef.current,
          processingInformation: {
            ...processingInformation,
            videoUploadValid: false,
          },
          // need to set id to DB model ID and not current randomly generated uuid to update
          id: videoRef.current?.modelId,
        };

        setVideo(nextVideoObj as Video);

        return;
      }

      if (
        message.done === true ||
        (message.noUpload === true && !waitForTranscodeComplete)
      ) {
        return onUploadDone();
      }

      onProgress(message.progress as number);
    },
    [onProgress, onUploadDone, setVideo, pushError, waitForTranscodeComplete]
  );

  const { data, error } = useVideoUploadProgressUpdatedSubscription({
    variables: {
      videoId: videoRef.current?.modelId ?? '',
      listenForTranscodedVideo: waitForTranscodeComplete,
    },
  });

  useEffect(() => {
    if (error) {
      logger.error(
        error,
        {
          message: 'Upload progress subscription error',
        },
        { feature: Feature.VideoUpload }
      );
    } else if (data) {
      handleSubscriptionData(data);
    }
  }, [error, data, handleSubscriptionData]);
};

export const UploadProgress: React.FC<
  React.PropsWithChildren<unknown>
> = () => {
  const [isComplete, setIsComplete] = useState(false);
  const [progressValue, setProgressValue] = useState(0);
  const [isWaitForIOSSafariFlashDone, setIsWaitForIOSSafariFlashDone] =
    useState(false);

  const {
    video: {
      uploadComplete,
      source,
      videoProperties: {
        mediaMetadataRotation,
        ingestionType,
        recordingClient,
      } = {},
      processingInformation: { videoUploadValid } = {},
    },
  } = useVideoContext();

  const isMeetingInProgress =
    recordingClient === 'meeting_bot' && !uploadComplete;

  const hasProcessingError = videoUploadValid === false;

  const waitForTranscodeComplete = shouldWaitForTranscodeComplete(
    mediaMetadataRotation
  );

  const sourceUrlIsTranscoded = source?.sourceUrlIsTranscoded || false;

  useEffect(() => {
    const flashingBarTimeout = setTimeout(() => {
      setIsWaitForIOSSafariFlashDone(true);
    }, 1000);

    return () => clearTimeout(flashingBarTimeout);
  }, []);

  useLoadingProgressHook({
    setProgressValue,
    setIsComplete,
  });

  if (
    hasProcessingError ||
    (uploadComplete && !waitForTranscodeComplete) ||
    (waitForTranscodeComplete &&
      (sourceUrlIsTranscoded || !isWaitForIOSSafariFlashDone))
  ) {
    return null;
  }

  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore linter assumes ingestionType is TS type causing errors
  if (!uploadComplete && Object.values(IngestionType).includes(ingestionType)) {
    return <LazyZoomIngestionModal />;
  }

  return (
    <LazyProgressLayer
      progressValue={progressValue}
      isComplete={isComplete}
      isMeetingInProgress={isMeetingInProgress}
    />
  );
};
