export enum RequestPlanUpgradeLocations {
  HEADER = 'header',
  PROFILE_DROPDOWN = 'profile_dropdown',
  AI_SIDEBAR_CTA = 'ai_sidebar_cta',
  AI_PROFILE_DROPDOWN = 'ai_profile_dropdown',
  AI_FTUX = 'ai_ftux',
  AI_TRIAL_ENDED_MODAL = 'ai_trial_ended_modal',
  MARKETING_SITE = 'marketing_site',
  PLAN_AND_BILLING = 'plan_and_billing',
  UPGRADE_BANNER = 'upgrade_banner',
  AI_CONSOLIDATED_EDIT_CTA = 'ai_consolidated_edit_cta',
  SEASONAL_LAUNCH_MODAL = 'seasonal_launch_modal',
  EDIT_AND_TRIM_LOCKED_BUTTON = 'edit_and_trim_locked_button',
  REMOVE_SILENCE_FILLER_WORDS_LOCKED_BUTTON = 'remove_silence_filler_words_locked_button',
  AUTO_CONTEXT_LOCKED_BUTTON = 'auto_context_locked_button',
  WORKFLOWS_LOCKED_BUTTON = 'workflows_locked_button',
  ADD_LINK_LOCKED_BUTTON = 'add_link_locked_button',
  TRIAL_PILL = 'trial_pill',
  VARIABLES = 'variables',
  AI_MEETING_RECAP_CTA = 'ai_meeting_recap_cta',
  USAGE_BASED_BANNER = 'usage_based_banner',
}
