// Only store constants for modals here
// that are called by the ModalComponents.
export enum ModalTypeEnum {
  ANON_CREATOR_SIGNUP_MODAL = 'ANON_CREATOR_SIGNUP_MODAL',
  HARD_GATE_COMMENT_EMOJI_MODAL = 'HARD_GATE_COMMENT_EMOJI_MODAL',
  HARD_GATE_VIEWS_MODAL = 'HARD_GATE_VIEWS_MODAL',
  RECORD_MEETING_MODAL = 'RECORD_MEETING_MODAL',
  AI_MEETING_NOTES_LOCATION_MODAL = 'AI_MEETING_NOTES_LOCATION_MODAL',
  CONFLUENCE_PAGE_CREATION_MODAL = 'CONFLUENCE_PAGE_CREATION_MODAL',
}
