// eslint-disable-next-line no-restricted-imports
import { useLazyQuery } from '@apollo/client';
import { useVideoContext } from '@js/common/video-player';
import React, { useEffect, useState } from 'react';

import { getTimeSavedText, getTimeSaved } from '@js/utilities/insights';

import { Arrange, Tooltip, Icon, Text, Spacer } from '@loomhq/lens';
import { SvgInfo } from '@loomhq/lens/icons/info';
import { HubDateRange } from '@loomhq/shared-utilities/constants/insights';

import InsightsHubButton from '../../insights-hub/insightsHubButton';
import InsightsHubIcon from '../../insights-hub/insightsHubIcon';
import getInsightsValueForTimeframes from './GetInsightsValueForTimeframes.graphql';

const InsightsMilestone = (): React.ReactElement => {
  const [milestoneText, setMilestoneText] = useState('');
  const [tooltipText, setTooltipText] = useState('');
  const {
    video: {
      isOwner,
      views,
      videoProperties: { playableDuration },
    },
  } = useVideoContext();
  const { total: videoViews = 0 } = views ?? {};
  const secondsSaved = getTimeSaved({
    videoViews,
    videoDuration: playableDuration || 0,
  });
  const timeSavedText = getTimeSavedText({ secondsSaved });
  // TODO: Replace with autogenerated hook
  const [getInsightsData, { data, loading }] = useLazyQuery(
    getInsightsValueForTimeframes,
    {
      variables: {
        dateRangeType: HubDateRange.MONTH,
        interval: 0,
      },
      fetchPolicy: 'cache-and-network',
      nextFetchPolicy: 'cache-first',
    }
  );
  const totalViewsThisMonth =
    data?.getInsightsValueForTimeframes?.owner?.videoView;

  useEffect(() => {
    if (videoViews === 1 || !timeSavedText) {
      getInsightsData();

      if (totalViewsThisMonth) {
        setMilestoneText(`${totalViewsThisMonth} views this month`);
      }
    } else if (timeSavedText) {
      setMilestoneText(`${timeSavedText} saved`);
      setTooltipText(
        `Every view on this video beyond the first view is one less time that you had to repeat yourself. Great work at scaling knowledge!`
      );
    }
  }, [videoViews, getInsightsData, timeSavedText, totalViewsThisMonth]);

  if (!videoViews || loading || !isOwner || !milestoneText) {
    return <></>;
  }

  return (
    <>
      <Arrange
        gap="small"
        justifyContent={{
          default: 'stretch',
          medium: 'space-between',
        }}
        autoFlow={{
          default: 'row',
          medium: 'column',
        }}
      >
        <Arrange gap="xsmall">
          <InsightsHubIcon size={3} />
          <Spacer left={0.5}></Spacer>
          <Text size="body-md" color="bodyDimmed" fontWeight="book">
            {milestoneText}
          </Text>

          {tooltipText && (
            <Tooltip content={tooltipText} maxWidth={40}>
              <Icon icon={<SvgInfo />} size={2.25} color="bodyDimmed" />
            </Tooltip>
          )}
        </Arrange>
        <InsightsHubButton
          buttonText="More insights"
          source="viewer-insights-share-page"
          buttonSize="small"
        />
      </Arrange>
    </>
  );
};

// eslint-disable-next-line import/no-default-export
export default InsightsMilestone;
