// DO NOT ADD TO THIS FILE. Instead add to the enums file.

// Only store constants for modals here
// that are called by the ModalComponents.

export const ADD_LOOM_SEARCH_MODAL = 'ADD_LOOM_SEARCH_MODAL';
export const ADD_VIDEO_TO_SPACE_SEARCH_MODAL =
  'ADD_VIDEO_TO_SPACE_SEARCH_MODAL';
export const ADMIN_DELETE_ACCOUNT_WARNING_MODAL =
  'ADMIN_DELETE_ACCOUNT_WARNING_MODAL';
export const ADMIN_FORCE_ADD_MEMBERS_CONFIRMATION_MODAL =
  'ADMIN_FORCE_ADD_MEMBERS_CONFIRMATION_MODAL';
export const ADMIN_SUSPEND_ACCOUNT_MODAL = 'ADMIN_SUSPEND_ACCOUNT_MODAL';
export const ANON_SHARE_GATE_MOBILE_MODAL = 'ANON_SHARE_GATE_MOBILE_MODAL';
export const ANON_SHARE_GATE_MODAL = 'ANON_SHARE_GATE_MODAL';
export const ARCHIVE_SPACE_CONFIRMATION = 'ARCHIVE_SPACE_CONFIRMATION';
export const AUTOJOIN_MODAL = 'AUTOJOIN_MODAL';
export const CANCEL_SCHEDULED_PAUSE_MODAL = 'CANCEL_SCHEDULED_PAUSE_MODAL';
export const CHECKLIST_RECORD_BUTTON_MODAL = 'CHECKLIST_RECORD_BUTTON_MODAL';
export const CONFIRM_DELETE_ITEM_MODAL = 'CONFIRM_DELETE_ITEM_MODAL';
export const CONTACT_SUPPORT_CONFIRMATION_MODAL =
  'CONTACT_SUPPORT_CONFIRMATION_MODAL';
export const CONTACT_SUPPORT_MODAL = 'CONTACT_SUPPORT_MODAL';
export const CREATE_NEW_WORKSPACE_MODAL = 'CREATE_NEW_WORKSPACE_MODAL';
export const CREATE_SPACE_MODAL = 'CREATE_SPACE_MODAL';
export const DATA_RETENTION_PREVIEW_MODAL = 'DATA_RETENTION_PREVIEW_MODAL';
export const DESTINATION_MOVE_MODAL = 'DESTINATION_MOVE_MODAL';
export const DESTINATION_SEARCH_MODAL = 'DESTINATION_SEARCH_MODAL';
export const DOWNLOAD_VIDEO_INFO_MODAL = 'DOWNLOAD_VIDEO_INFO_MODAL';
export const EDIT_SPACE_MODAL = 'EDIT_SPACE_MODAL';
export const END_USER_SESSION_MODAL = 'END_USER_SESSION_MODAL';
export const EXT_SOURCE_WORKSPACE_CONTACTS_MODAL =
  'EXT_SOURCE_WORKSPACE_CONTACTS_MODAL';
export const FOLDER_MOVE_CONFIRMATION_MODAL = 'FOLDER_MOVE_CONFIRMATION_MODAL';
export const FOLDER_SETTINGS_MODAL = 'FOLDER_SETTINGS_MODAL';
export const FORGOT_PASSWORD_MODAL = 'FORGOT_PASSWORD_MODAL';
export const IMPORT_RECORDINGS_MODAL = 'IMPORT_RECORDINGS_MODAL';
export const LEAVE_WORKSPACE_CONFIRMATION = 'LEAVE_WORKSPACE_CONFIRMATION';
export const MANUAL_PAYMENT_MODAL = 'MANUAL_PAYMENT_MODAL';
export const PAUSE_SUBSCRIPTION_MODAL = 'PAUSE_SUBSCRIPTION_MODAL';
export const PRODUCT_SELECTION_MODAL = 'PRODUCT_SELECTION_MODAL';
export const PURCHASE_AI_MODAL = 'PURCHASE_AI_MODAL';
export const REQUEST_UPGRADE_MODAL = 'REQUEST_UPGRADE_MODAL';
export const RESUME_PAUSED_SUBSCRIPTION_MODAL =
  'RESUME_PAUSED_SUBSCRIPTION_MODAL';
export const ROLE_MANDATORY_MODAL = 'ROLE_MANDATORY_MODAL';
export const SCREENSHOT_SETTINGS_MODAL = 'SCREENSHOT_SETTINGS_MODAL';
export const SDK_RECORDING_LOADING_MODAL = 'SDK_RECORDING_LOADING_MODAL';
export const SHARE_FOLDER_MODAL = 'SHARE_FOLDER_MODAL';
export const SHARE_RECORD_REPLY_SIGNUP_MODAL =
  'SHARE_RECORD_REPLY_SIGNUP_MODAL';
export const SHARE_UI_MODAL = 'SHARE_UI_MODAL';
export const SHOW_FOLLOWS_MODAL = 'SHOW_FOLLOWS_MODAL';
export const SIGNUP_MODAL = 'SIGNUP_MODAL';
export const SLACK_WORKSPACE_CONNECTED_MODAL =
  'SLACK_WORKSPACE_CONNECTED_MODAL';
export const SPACES_FOLDER_MOVE_MODAL = 'SPACES_FOLDER_MOVE_MODAL';
export const TEAM_INVITE_MODAL = 'TEAM_INVITE_MODAL';
export const UNARCHIVE_SPACE_CONFIRMATION = 'UNARCHIVE_SPACE_CONFIRMATION';
export const VERIFY_EMAIL_MODAL = 'VERIFY_EMAIL_MODAL';
export const VIDEO_MOVE_CONFIRMATION_MODAL = 'VIDEO_MOVE_CONFIRMATION_MODAL';
export const VIDEO_MOVE_MODAL = 'VIDEO_MOVE_MODAL';
export const VIDEO_THUMBNAIL_MODAL = 'VIDEO_THUMBNAIL_MODAL';
export const WORKFLOWS_MODAL = 'WORKFLOWS_MODAL';
export const WORKSPACE_CONFIGURATION_MODAL = 'WORKSPACE_CONFIGURATION_MODAL';
export const WORKSPACE_CONTACTS_CONFIRMATION_MODAL =
  'WORKSPACE_CONTACTS_CONFIRMATION_MODAL';
export const WORKSPACE_SELECTOR_MODAL = 'WORKSPACE_SELECTOR_MODAL';
