import { COMMUNITY_LOOMS_URI } from '@js/constants/routes';

// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';
import { useFlagIsActivated } from '@js/hooks/featureFlag';
import _range from 'lodash/range';

import React from 'react';

import {
  Link,
  Text,
  Tooltip,
  Icon,
  Container,
  Spacer,
  Arrange,
} from '@loomhq/lens';
import { SvgInfo } from '@loomhq/lens/icons/info';

import {
  ROLLOUT_COMMUNITY_LOOMS,
  ROLLOUT_COMMUNITY_LOOMS_VARIANTS,
} from '@loomhq/shared-utilities/constants/featureFlag';

import GetCommunityLoomsSortedIdsQuery from '../../empty-state/community-empty-state/getCommunityLoomIdsForEmptyStates.graphql';
import InlinePlayerGridModule from '../inline-player-grid-module';
import TrendingVideoCardSkeleton from '../skeleton/TrendingVideoCardSkeleton';
import useTrendingVideosPerRow from '../useTrendingVideosPerRow';
import styles from './style.module.css';

const TOOLTIP_TEXT = `See how Loom can save you time at work from Loom employees and people like you.`;

export const CommunityCarouselHome = (): JSX.Element | null => {
  const shouldShowCommunityLooms = useFlagIsActivated({
    flag: ROLLOUT_COMMUNITY_LOOMS,
    activationValues: ROLLOUT_COMMUNITY_LOOMS_VARIANTS,
  });
  const trendingCardsPerRow = useTrendingVideosPerRow();
  const trendingCards = _range(trendingCardsPerRow).map(i => (
    <TrendingVideoCardSkeleton key={i} />
  ));

  // TODO: Replace with autogenerated hook
  const { data, loading } = useQuery(GetCommunityLoomsSortedIdsQuery, {
    variables: { returnAll: true },
    fetchPolicy: 'no-cache',
  });

  const videos = data?.getCommunityLoomIdsForEmptyStates?.starterVideos;

  if (
    !shouldShowCommunityLooms ||
    ((!videos || videos.length < 0) && !loading)
  ) {
    return null;
  }

  return loading ? (
    <>
      <Container
        height="small"
        width="200px"
        backgroundColor="disabledBackground"
        radius="medium"
      />
      <Spacer bottom="large" />
      <Arrange
        gap="large"
        columns={`repeat(${trendingCardsPerRow}, minmax(0, 1fr))`}
      >
        {trendingCards}
      </Arrange>
      <Spacer bottom="large" />
    </>
  ) : (
    <InlinePlayerGridModule
      title={
        <Text htmlTag="h2" size="body-lg" fontWeight="bold" alignment="left">
          Inspiration from the{' '}
          <Link href={COMMUNITY_LOOMS_URI}>Loom Community</Link>
        </Text>
      }
      videos={videos}
      tooltip={<ToolTip />}
    />
  );
};

export const ToolTip = (): JSX.Element => {
  return (
    <Tooltip
      content={TOOLTIP_TEXT}
      placement="rightCenter"
      triggerOffset={18}
      tabIndex={-1}
    >
      <button className={styles.tooltipButton}>
        <Container backgroundColor="highlight" padding=".375rem" radius="100">
          <Arrange>
            <Icon altText={TOOLTIP_TEXT} size={2} icon={<SvgInfo />} />
          </Arrange>
        </Container>
      </button>
    </Tooltip>
  );
};
