import { ObservableSubscription } from '@apollo/client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useDispatch } from 'react-redux';

import { Feature, Team } from '@loomhq/shared-utilities/constants/product';
import {
  SUCCESS as TRANSCRIPTION_STATUS_SUCCESS,
  TRANSCRIPTION_STATUSES,
} from '@loomhq/shared-utilities/constants/videoTranscript';
import {
  isTerminalTranscriptionStatus,
  isTranscriptionStatusContainingTranscript,
} from '@loomhq/shared-utilities/utilities/transcriptionUtils';

import { updateRetranscriptionStatus } from '@js/actions/shareVideo';

import { useErrorBar } from '@js/common/error-management/error-bar/useErrorBar';
import {
  useTranscript,
  useUserCanAccessTranscript,
} from '@js/common/transcripts';
import { useVideoPasswordContext } from '@js/common/video-password';
import { useVideoContext } from '@js/common/video-player';
import { ErrorSeverities } from '@js/constants/error-severities';
import { updateTranscriptPhrases } from '@js/reducers/transcription';
import fetch from '@js/utilities/fetch';
// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';
import * as loggerx from '@js/utilities/loggerx';
import { RetranscriptionStatus } from '@js/utilities/transcript/statuses';

import {
  FetchTranscriptStatusChangedSubscription,
  FetchTranscriptStatusChangedSubscriptionVariables,
  FetchTranscriptStatusChangedDocument,
} from './FetchTranscriptStatusChanged.generated';

import { useFetchTranscriptStatusForFetchTranscriptLazyQuery } from './FetchTranscriptStatusForFetchTranscript.generated';
import {
  FetchVideoTranscriptForFetchTranscriptQuery,
  useFetchVideoTranscriptForFetchTranscriptLazyQuery,
} from './FetchVideoTranscriptForFetchTranscript.generated';

import { useTranscriptStore } from '../useTranscriptStore';
import { useGetMigrationTranscriptValues } from '@js/common/transcripts/useGetMigrationTranscriptValues';

const FALLBACK_TIMEOUT = 30_000;

type VideoTranscriptDetails = Extract<
  FetchVideoTranscriptForFetchTranscriptQuery['fetchVideoTranscript'],
  { __typename: 'VideoTranscriptDetails' }
>;

export const FetchTranscriptWithGql = (): null => {
  const dispatch = useDispatch();
  const { showErrorBar } = useErrorBar();
  const {
    video: { activeVideoTranscriptId, id: videoId },
  } = useVideoContext();
  const { password: videoPlayerPassword } = useVideoPasswordContext();

  const [didFirstFetch, setDidFirstFetch] = useState(false);
  const { retranscriptionStatus } = useGetMigrationTranscriptValues();
  const { transcript, transcriptStatus } = useTranscript();

  const userCanAccessTranscript = useUserCanAccessTranscript();
  const { password } = useVideoPasswordContext();
  const { setTranscript, setRetranscriptionStatus } = useTranscriptStore();

  const client = getGraphQLClient();

  const subscriptionRef = useRef<ObservableSubscription | null>(null);

  const fallbackIntervalRef = useRef<ReturnType<typeof setInterval> | null>(
    null
  );

  // useFetchVideoTranscriptForFetchTranscriptLazyQuery replaces the fetchTranscriptPhrases action creator
  const [fetchVideoTranscriptQuery, { error: fetchTranscriptError }] =
    useFetchVideoTranscriptForFetchTranscriptLazyQuery({
      fetchPolicy: 'no-cache',
      onCompleted: async data => {
        const { fetchVideoTranscript } = data;

        if (fetchVideoTranscript?.__typename === 'GenericError') {
          const errorMessage = fetchVideoTranscript?.message;

          showErrorBar({
            message: 'Oops! Failed to fetch transcript.',
            severity: ErrorSeverities.ERROR,
          });
          loggerx.error(
            errorMessage,
            {
              message: `Error fetching transcript for video id ${videoId}: ${errorMessage}`,
              videoId,
            },
            { team: Team.ShareAndTransform }
          );

          return;
        }

        // Creating new object to avoid running into a TypeError when deleting attributes from fetchVideoTranscript
        const fetchVideoTranscriptCleaned: Omit<
          VideoTranscriptDetails,
          | '__typename'
          | 'captions_url'
          | 'captions_source_url'
          | 'filler_word_removal'
          | 'filler_words'
        > = {
          ...fetchVideoTranscript,
        };

        ['__typename', 'captions_url', 'captions_source_url'].forEach(
          key => delete fetchVideoTranscriptCleaned[key]
        );

        // detect if this update was due to a retranscription
        const transcriptionFinished = isTerminalTranscriptionStatus(
          fetchVideoTranscript.transcription_status
        );

        if (
          retranscriptionStatus === RetranscriptionStatus.STARTED &&
          transcriptionFinished
        ) {
          dispatch(updateRetranscriptionStatus(RetranscriptionStatus.FINISHED));
          setRetranscriptionStatus(RetranscriptionStatus.FINISHED);
        }

        const sourceUrl = fetchVideoTranscriptCleaned?.source_url || null;
        const status = (fetchVideoTranscriptCleaned?.transcription_status ||
          null) as 'partial' | 'success' | null;

        const isTranscriptAvailable = Boolean(
          status &&
            isTranscriptionStatusContainingTranscript(status) &&
            sourceUrl
        );

        if (!isTranscriptAvailable || !sourceUrl) {
          return;
        }

        const resp = await fetch(sourceUrl);

        if (!resp.ok) {
          loggerx.error(
            'Failed to fetch transcript json',
            {
              message: `Failed to fetch transcript json`,
              videoId,
            },
            { team: Team.ShareAndTransform }
          );

          return;
        }

        const phrasesObj = await resp.json();

        // Note: it's possible that a video may have a phrase with only punctuations (e.g. the last phrase has "." only)
        // In this case, the phrase will have ts = -1 which will break the transcript panel, so filtering out those phrase here.
        if (phrasesObj?.phrases) {
          const filteredPhrases = phrasesObj.phrases.filter(
            phrase => phrase?.ts >= 0
          );

          phrasesObj.phrases = filteredPhrases;
        }

        dispatch(updateTranscriptPhrases(phrasesObj));
        setTranscript(phrasesObj);
      },
      onError: err => {
        showErrorBar({
          message: 'Oops! Failed to fetch transcript.',
          severity: ErrorSeverities.ERROR,
        });
        loggerx.error(
          err,
          {
            message: `Error fetching transcript for video id ${videoId}: ${err}`,
            videoId,
          },
          { team: Team.ShareAndTransform }
        );
      },
    });

  // Wrapper function for fetchVideoTranscriptQuery as there is no skip functionality in the lazy query
  const fetchTranscriptPhrases = useCallback((): void => {
    if (!activeVideoTranscriptId) {
      return;
    }

    fetchVideoTranscriptQuery({
      variables: {
        videoId,
        password: password || null,
      },
    });
  }, [activeVideoTranscriptId, fetchVideoTranscriptQuery, password, videoId]);

  // useFetchTranscriptStatusForFetchTranscriptLazyQuery replaces fetchTranscriptStatus action creator
  const [fetchTranscriptStatusQuery] =
    useFetchTranscriptStatusForFetchTranscriptLazyQuery({
      fetchPolicy: 'no-cache',
      onCompleted: data => {
        const { fetchVideoTranscript } = data;

        if (fetchVideoTranscript?.__typename !== 'VideoTranscriptDetails') {
          const errorMessage = fetchVideoTranscript?.message;

          loggerx.error(
            `Failed to fetch VideoTranscriptDetails for video id ${videoId}: ${errorMessage}`,
            {
              videoId,
            },
            {
              feature: Feature.TranscriptPanel,
            }
          );

          return;
        }

        const status = fetchVideoTranscript?.transcription_status;

        handleTranscriptStatusUpdate(status);
      },
      onError: err => {
        loggerx.error(
          err,
          {
            message: `Error while fetching transcript status for ${videoId}`,
            videoId,
          },
          { team: Team.ShareAndTransform }
        );
      },
    });

  const handleTranscriptStatusUpdate = useCallback(
    (status: any) => {
      // check if we are still waiting for the final transcript
      if (
        !isTerminalTranscriptionStatus(status) &&
        TRANSCRIPTION_STATUSES.includes(status)
      ) {
        return;
      }

      fetchTranscriptPhrases();

      if (subscriptionRef.current) {
        subscriptionRef.current.unsubscribe();
        subscriptionRef.current = null;
      }

      if (fallbackIntervalRef.current) {
        clearInterval(fallbackIntervalRef.current);
        fallbackIntervalRef.current = null;
      }
    },
    [fetchTranscriptPhrases]
  );

  // Initial fetching
  useEffect(() => {
    if (activeVideoTranscriptId && userCanAccessTranscript && !didFirstFetch) {
      fetchTranscriptPhrases();

      setDidFirstFetch(true);
    }
  }, [
    activeVideoTranscriptId,
    didFirstFetch,
    dispatch,
    fetchTranscriptPhrases,
    userCanAccessTranscript,
    videoPlayerPassword,
  ]);

  // Subscribes and watches for transcription status changes
  useEffect(() => {
    const finalTranscriptMissing =
      !transcript || transcriptStatus !== TRANSCRIPTION_STATUS_SUCCESS;

    if (
      !activeVideoTranscriptId ||
      !userCanAccessTranscript ||
      !didFirstFetch ||
      !finalTranscriptMissing ||
      fetchTranscriptError
    ) {
      return;
    }

    try {
      if (
        isTerminalTranscriptionStatus(transcriptStatus) ||
        subscriptionRef.current
      ) {
        return;
      }

      // Keeping this as a client.subscribe rather than a subscription hook
      // as we need a way to unsubscribe from the subscription which is not currently possible with the use hook
      // When we move to storing all transcript data in apollo graphql cache
      // we can change to a subscribeToMore and call wherever transcript status and phases are needed & localized to the components
      // Until then since we are relying on redux to store transcript data for multiple components
      subscriptionRef.current = client
        .subscribe<
          FetchTranscriptStatusChangedSubscription,
          FetchTranscriptStatusChangedSubscriptionVariables
        >({
          variables: { videoId },
          query: FetchTranscriptStatusChangedDocument,
        })
        .subscribe(body => {
          const {
            data: {
              // @ts-expect-error FIXME: transcriptStatus is not guaranteed here
              transcriptStatus: { status },
            },
          } = body;

          handleTranscriptStatusUpdate(status);
        });

      // Just in case the transcript completed between the initial fetch and the subscribe
      // We fetch here to avoid a race condition
      fetchTranscriptPhrases();

      // If we didn't receive a response from the server in FALLBACK_TIMEOUT sec, something probably went wrong.
      // So we're better off unsubscribing and fetching the status manually
      fallbackIntervalRef.current = setInterval(() => {
        fetchTranscriptStatusQuery({
          variables: {
            videoId,
            password: videoPlayerPassword || null,
          },
        });
      }, FALLBACK_TIMEOUT);
    } catch (err) {
      loggerx.error(
        err,
        {
          message: `Error subscribing to transcript status for video id ${videoId}: ${err}`,
          videoId,
        },
        { feature: Feature.TranscriptInsights }
      );
    }
  }, [
    activeVideoTranscriptId,
    didFirstFetch,
    dispatch,
    transcript,
    userCanAccessTranscript,
    fetchTranscriptError,
    videoId,
    videoPlayerPassword,
    password,
    transcriptStatus,
    fetchTranscriptPhrases,
    fetchTranscriptStatusQuery,
    handleTranscriptStatusUpdate,
    client,
  ]);

  useEffect(() => {
    // only for cleanup
    return () => {
      if (subscriptionRef.current) {
        subscriptionRef.current.unsubscribe();
        subscriptionRef.current = null;
      }

      if (fallbackIntervalRef.current) {
        clearInterval(fallbackIntervalRef.current);
        fallbackIntervalRef.current = null;
      }
    };
  }, []);

  return null;
};
