// NOTE: Please stop adding/hoisting new functions into this file. Instead, colocate hooks with the files that use them.

/* eslint-disable  @typescript-eslint/no-explicit-any */
// eslint-disable-next-line no-restricted-imports
import { useLazyQuery, useQuery } from '@apollo/client';

import { useVideoContext } from '@js/common/video-player/context';

import { isFromPublicSharePage } from '@js/utilities/url';

import { routingUtils, urlUtils } from '@loomhq/shared-utilities';
import { EntityRoutingHeader } from '@loomhq/shared-utilities/constants/siteEntities';
import { isAliasVideoUrl } from '@js/utilities/video';

import CheckPassword from './hooks/CheckPassword.gql';
import FetchVideoData from './hooks/FetchVideoData.gql';

const { getVideoIdFromPageUrl } = urlUtils;

// Little hack to have getLoomPlayerLogs in the window object without having eslint scream.
declare global {
  interface Window {
    getLoomPlayerLogs: () => any[];
  }
}

// will also differentiate embed players as video comments on the share page as embed playerss
export const useIsVideoEmbedded = (): boolean => {
  const { video } = useVideoContext();

  if (isAliasVideoUrl(window.location.pathname)) {
    return false;
  }

  if (video?.platform === 'slackPlayer') {
    return true;
  }

  const isOnSharePage = isFromPublicSharePage().fromPublicSharePage;

  if (!isOnSharePage) {
    return true;
  }

  const sharePageVideoId = getVideoIdFromPageUrl(window.location.href);

  const embedPlayerVideoId = video.modelId;

  return sharePageVideoId !== embedPlayerVideoId;
};

export function useCheckPassword(): any {
  // TODO: Replace with autogenerated hook
  const [checkPassword, { loading, error, data }] = useLazyQuery(
    CheckPassword,
    {
      fetchPolicy: 'no-cache',
    }
  );

  return [checkPassword, { loading, error, data }];
}

export function useFetchVideoData(videoId: string, skip = false): any {
  // TODO: Replace with autogenerated hook
  const { loading, error, data } = useQuery(FetchVideoData, {
    variables: { id: videoId },
    skip,
    context: {
      headers: {
        [EntityRoutingHeader]: routingUtils.encodeEntityRoutingMetadata({
          entityType: 'video',
          entityId: videoId,
        }),
      },
    },
  });

  return { loading, error, data };
}
