/* eslint-disable @loomhq/loom/no-js-extension */

import {
  PROFILE_FOLLOWED,
  PROFILE_FOLLOW_SUGGESTION_DISPOSITIONED,
} from '@js/constants/events';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';

import { useCurrentUserSelector } from '@js/common/current-user';
import React from 'react';

import { Arrange } from '@loomhq/lens';
import { FollowStreamType } from '@loomhq/shared-utilities/constants/follows';
import { MemberPropertyEnum } from '@loomhq/shared-utilities/constants/memberProperties';
import { useUpdateMemberProperty } from '@js/hooks/memberProperties';
import { track } from '@js/utilities/analytics';

import ToggleFollowingProfile from './ToggleFollowingProfile.graphql';
import {
  AddSuggestedFollow,
  RemoveSuggestedFollow,
} from './ToggleSuggestedFollow';
import styles from './styles.module.less';

const SuggestedProfileFollow = ({ profile, ProfileLink, declinedStreams }) => {
  const userId = useCurrentUserSelector(user => user.id, undefined);

  // TODO: Replace with autogenerated hook
  const [followProfile] = useMutation(ToggleFollowingProfile, {
    refetchQueries: ['GetUserFollowsProfile', 'GetUserFollowedStreams'],
    awaitRefetchQueries: true,
  });

  const { updateMemberProperty } = useUpdateMemberProperty(
    MemberPropertyEnum.DECLINED_SUGGESTED_FOLLOW_STREAMS,
    { refetchQueries: ['GetSuggestedStreams'] }
  );

  const addProfile = () => {
    followProfile({ variables: { follow: true, profileId: profile.user.id } });

    track(PROFILE_FOLLOWED, {
      user_id: userId,
      profile_id: profile.user.id,
      context_page_path: window.location.pathname,
    });

    track(PROFILE_FOLLOW_SUGGESTION_DISPOSITIONED, {
      user_id: userId,
      profile_user_id: profile.user.id,
      surface: 'sidebar',
      is_accepted: true,
    });
  };

  const removeProfile = () => {
    updateMemberProperty([
      ...declinedStreams,
      {
        type: FollowStreamType.USER_PROFILE,
        value: profile.user.id,
      },
    ]);

    track(PROFILE_FOLLOW_SUGGESTION_DISPOSITIONED, {
      user_id: userId,
      profile_user_id: profile.user.id,
      surface: 'sidebar',
      is_accepted: false,
    });
  };

  return (
    <ProfileLink
      profile={profile}
      className={styles.suggestedStream}
      actionElement={
        <Arrange gap="xxsmall">
          <AddSuggestedFollow onClick={addProfile} />
          <RemoveSuggestedFollow onClick={removeProfile} />
        </Arrange>
      }
    />
  );
};

// eslint-disable-next-line import/no-default-export
export default SuggestedProfileFollow;
