/* eslint-disable @loomhq/loom/no-js-extension */

import {
  TAG_FOLLOWED,
  TAG_FOLLOW_SUGGESTION_DISPOSITIONED,
} from '@js/constants/events';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';

import { useCurrentUserSelector } from '@js/common/current-user';
import React from 'react';

import { Arrange } from '@loomhq/lens';
import { FollowStreamType } from '@loomhq/shared-utilities/constants/follows';
import { MemberPropertyEnum } from '@loomhq/shared-utilities/constants/memberProperties';
import ToggleFollowingTag from '@js/common/follows/ToggleFollowingTag.graphql';
import { useUpdateMemberProperty } from '@js/hooks/memberProperties';
import { track } from '@js/utilities/analytics';

import {
  AddSuggestedFollow,
  RemoveSuggestedFollow,
} from './ToggleSuggestedFollow';
import styles from './styles.module.less';

const SuggestedTagFollow = ({ tag, TagLink, declinedStreams }) => {
  const userId = useCurrentUserSelector(user => user.id, undefined);

  // TODO: Replace with autogenerated hook
  const [followTag] = useMutation(ToggleFollowingTag, {
    refetchQueries: ['GetUserFollowsTag', 'GetUserFollowedStreams'],
    awaitRefetchQueries: true,
  });

  const { updateMemberProperty } = useUpdateMemberProperty(
    MemberPropertyEnum.DECLINED_SUGGESTED_FOLLOW_STREAMS,
    { refetchQueries: ['GetSuggestedStreams'] }
  );

  const addTag = () => {
    followTag({ variables: { follow: true, tag: tag.name } });

    track(TAG_FOLLOW_SUGGESTION_DISPOSITIONED, {
      user_id: userId,
      surface: 'sidebar',
      is_accepted: true,
    });

    track(TAG_FOLLOWED, {
      user_id: userId,
      surface: 'sidebar',
      context_page_path: window.location.pathname,
    });
  };

  const removeTag = () => {
    updateMemberProperty([
      ...declinedStreams,
      { type: FollowStreamType.WORKSPACE_TAG, value: tag.name },
    ]);

    track(TAG_FOLLOW_SUGGESTION_DISPOSITIONED, {
      user_id: userId,
      surface: 'sidebar',
      is_accepted: false,
    });
  };

  return (
    <TagLink
      key={tag.name}
      tag={tag}
      className={styles.suggestedStream}
      actionElement={
        <Arrange gap="xxsmall">
          <AddSuggestedFollow onClick={addTag} />
          <RemoveSuggestedFollow onClick={removeTag} />
        </Arrange>
      }
    />
  );
};

// eslint-disable-next-line import/no-default-export
export default SuggestedTagFollow;
