// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';

import React from 'react';

import { Arrange, Container, Spacer, Switch, Text } from '@loomhq/lens';
import { SpacesAvatar } from '@js/common/spaces';

import GetPrimarySpace from '@js/components/spaces/graphql/GetPrimarySpace.graphql';
import { useGetSelectedWorkspace } from '@js/hooks/workspace';

import { VideoCardSpace } from '../video-card/types';

const ShareToggle = ({
  isSwitchDisabled,
  onChange,
  spaces,
}: {
  isSwitchDisabled: boolean;
  onChange?: (
    newSpaces: VideoCardSpace[],
    oldSpaces: VideoCardSpace[],
    toastMessage: string
  ) => void;
  spaces: VideoCardSpace[];
}): JSX.Element => {
  const workspace = useGetSelectedWorkspace();
  // TODO: Replace with autogenerated hook
  const { data } = useQuery(GetPrimarySpace);
  const currentSpaceIds = spaces?.map(space => space.id);

  const primarySpace = data?.getPrimarySpace?.space;
  const onToggleSwitch = (checked: boolean) => {
    if (!onChange) {
      return;
    }

    let newSpaces;
    let toast;

    if (checked) {
      newSpaces = [...(spaces || []), primarySpace];
      toast = `A video was shared to ${primarySpace.name}`;
    } else {
      newSpaces = spaces?.filter(space => space.id !== primarySpace.id);
      toast = `A video was unshared from ${primarySpace.name}`;
    }

    onChange(newSpaces, spaces || [], toast);
  };

  return (
    <>
      <Container
        padding="small"
        radius="medium"
        backgroundColor="backgroundSecondary"
      >
        <Arrange justifyContent="space-between">
          <Container paddingLeft="small">
            <Arrange gap="small" alignItems="start">
              <Container>
                <SpacesAvatar spaceName={primarySpace?.name} />
              </Container>
              <Container>
                <Text fontWeight="bold" size="body-md">
                  Share to {primarySpace?.name}
                </Text>
                <Spacer top="xsmall" />
                <Text color="grey6" size="body-sm">
                  Make your video discoverable to anyone in {workspace.name}
                </Text>
              </Container>
            </Arrange>
          </Container>
          <Container>
            <Switch
              size="medium"
              isActive={currentSpaceIds?.includes(primarySpace?.id)}
              isDisabled={isSwitchDisabled}
              onChange={e =>
                onToggleSwitch((e.target as HTMLInputElement).checked)
              }
            />
          </Container>
        </Arrange>
      </Container>
    </>
  );
};

// eslint-disable-next-line import/no-default-export
export default ShareToggle;
