// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';

import { SpacePrivacy } from '@js/globalTypes.generated';

import GetSuggestedSpaces from './GetSuggestedSpaces.graphql';

export type SuggestedSpace = {
  id: string;
  name: string;
  is_primary: boolean;
  isArchived: boolean;
  privacy: SpacePrivacy | null;
};

const MAX_SPACES = 30;
const MAX_RECOMMENDATIONS = 3;

// eslint-disable-next-line import/no-default-export
export default function useSuggestedSpaces(): SuggestedSpace[] | null {
  // TODO: Replace with autogenerated hook
  const { data } = useQuery(GetSuggestedSpaces, {
    variables: {
      recommendedSpaceLimit: MAX_SPACES,
    },
  });

  if (!data) {
    return null;
  }

  const primarySpace = data?.primarySpace?.space;

  const spacesFromQuery =
    data?.recommendedSpaces?.recommendations?.nodes
      .map(node => node?.space)
      .filter(Boolean)
      .filter(space => !space?.is_primary) || [];
  const indexToSlice = Math.min(
    MAX_RECOMMENDATIONS,
    data?.recommendedSpaces?.totalRecommendations
  );
  const recommendedSpaces = spacesFromQuery.slice(0, indexToSlice);
  const spacesUserIsPartOf = [
    ...spacesFromQuery.slice(indexToSlice, spacesFromQuery.length),
  ]
    .filter(Boolean)
    .sort((a, b) => a.name.localeCompare(b.name));

  return [primarySpace, ...recommendedSpaces, ...spacesUserIsPartOf].filter(
    Boolean
  );
}
