import { ErrorSeverities } from '@js/constants/error-severities';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';
import { useErrorBar } from '@js/common/error-management/error-bar/useErrorBar';
import { useVideoPasswordContext } from '@js/common/video-password';
import { useVideoContext } from '@js/common/video-player';
import { useErrorStore } from '@js/components/video-player-fresh/error-layer/ErrorStoreProvider';
import { CommentOrReply } from '@js/pages/share/common/comments/commentOrReply';
import { isReply } from '@js/pages/share/common/comments/isReply';
import * as logger from '@js/utilities/loggerx';

import { Feature } from '@loomhq/shared-utilities/constants/product';

import EditComment from './EditComment.gql';

const COMMENT_EDIT_ERROR = 'Error editing comment';

type EditCommentParams = {
  comment: CommentOrReply; // need currentComment to be able to find the comment/reply in the cache to update locally
  newContent: string;
};

export function useEditComment(
  currentComment: CommentOrReply,
  trackEditComment: () => void
): (params: EditCommentParams) => void {
  const { video } = useVideoContext();
  const { password } = useVideoPasswordContext();
  const { pushError } = useErrorStore();
  const { showErrorBar } = useErrorBar();

  const editComment = ({ comment, newContent }: EditCommentParams): void => {
    editCommentInternal({
      variables: {
        id: comment.id,
        type: isReply(comment) ? 'REPLY' : 'COMMENT',
        videoId: video.modelId,
        password,
        content: newContent,
      },
    });
  };

  type EditCommentType = {
    __typename: string;
    success?: boolean;
    message?: string;
  };

  // needed to break up to use hook in onSave function
  // TODO: Replace with autogenerated hook
  const [editCommentInternal] = useMutation(EditComment, {
    optimisticResponse: {
      editComment: { __typename: 'editCommentPayload', success: true },
    },
    onError: err => {
      pushError(COMMENT_EDIT_ERROR);
      showErrorBar({
        message: 'Failed to edit comment.',
        severity: ErrorSeverities.ERROR,
      });
      logger.error(
        err,
        {
          message: COMMENT_EDIT_ERROR,
          error: err,
        },
        { feature: Feature.CommentReactions }
      );
    },
    update: (cache, { data }, { variables }) => {
      const response: EditCommentType | undefined = data?.editComment;

      // if there are no errors in mutation, update cache
      if (response?.success) {
        cache.modify({
          id: cache.identify(currentComment),
          fields: {
            content: () => variables?.content,
            edited: () => true,
            inFlightContent: () => null,
          },
        });
      } else {
        cache.modify({
          id: cache.identify(currentComment),
          fields: {
            inFlightContent: () => variables?.content,
          },
        });

        const defaultMessage = 'Failed to update comment';
        let errorMessage = defaultMessage;

        if (response?.__typename === 'InvalidRequestWarning') {
          errorMessage += `: ${response.message}`;
        }

        pushError(COMMENT_EDIT_ERROR);
        logger.error(
          errorMessage,
          {
            message: COMMENT_EDIT_ERROR,
          },
          { feature: Feature.CommentReactions }
        );
      }
    },
    onCompleted: () => {
      // analytics tracking
      trackEditComment();
    },
  });

  return editComment;
}
