import React from 'react';

import { Text } from '@loomhq/lens';

const GENERATED_BY_LOOM = 'Generated by Loom AI';

export const GeneratedByLoom = (): JSX.Element => {
  return (
    <Text size="body-sm" color="bodyDimmed">
      {GENERATED_BY_LOOM}
    </Text>
  );
};
