import { isDevOrTest } from '@js/constants/environment';

import AnalyticsWebClient, {
  userType,
  tenantType,
} from '@atlassiansox/analytics-web-client';

import { selectFromCurrentUserCache } from '@js/common/current-user/cache/selectFromCurrentUserCache';
import { selectIsCurrentUserLoggedInFromCache } from '@js/common/current-user/cache/selectIsCurrentUserLoggedInFromCache';
import { selectWorkspaceId } from '@js/common/current-user/schema/selectors/selectWorkspaceId';
// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';
import * as loggerx from '@js/utilities/loggerx';

import { Feature } from '@loomhq/shared-utilities/constants/product';

import { GetVideoSiteIdDocument } from './GetVideoSiteId.generated';
import { init } from './client';
import { getVideoIdFromCurrentUrl } from './utilities/getVideoIdFromCurrentUrl';

import type { UserInfo } from './types';

// Flag to track if we've started setting user info & tenant info
let isSettingUp = false;

const getUserInfo = () => {
  try {
    const isLoggedIn = selectIsCurrentUserLoggedInFromCache();
    const atlassianUserId = selectFromCurrentUserCache(user => user.aaId, '');
    const loomUserId = selectFromCurrentUserCache(user => user.id, NaN);

    let maybeUserSiteId = '';

    if (isLoggedIn && !isDevOrTest) {
      maybeUserSiteId = selectFromCurrentUserCache(user => {
        const org = user.memberships?.[0]?.organization;
        return org?.site_id || '';
      }, '');
    }

    const anonAaid = new URLSearchParams(window.location.search).get(
      'anonViewerAaid'
    );

    const isAtlassianMastered = Boolean(maybeUserSiteId);
    const userAccountType =
      isAtlassianMastered || Boolean(anonAaid) ? 'atlassian' : 'loom';
    const userDataMap: Record<string, UserInfo> = {
      atlassian: {
        userIdType: userType.ATLASSIAN_ACCOUNT,
        userId: (atlassianUserId?.toString() || anonAaid) ?? '',
        siteId: maybeUserSiteId,
      },
      loom: {
        userIdType: userType.LOOM,
        userId: String(loomUserId) || '',
        siteId: undefined,
      },
    };

    return userDataMap[userAccountType];
  } catch (error) {
    loggerx.error('Error setting user info for analytics', error, {
      feature: Feature.AtlassianAnalytics,
    });
  }
};

const getTenantInfo = () => {
  try {
    const maybeVideoId = getVideoIdFromCurrentUrl();
    const maybeUserWorkspaceId = selectFromCurrentUserCache(
      user => selectWorkspaceId(user),
      null
    );

    // Get user site ID from cache (was missing in the original implementation)
    const maybeUserSiteId = selectFromCurrentUserCache(user => {
      const org = user.memberships?.[0]?.organization;
      return org?.site_id || '';
    }, '');

    // Check for video data in Apollo cache (synchronously)
    if (maybeVideoId) {
      try {
        const client = getGraphQLClient();

        const cacheData = client.readQuery({
          query: GetVideoSiteIdDocument,
          variables: { videoId: maybeVideoId },
        });

        if (cacheData?.getVideo?.__typename === 'RegularUserVideo') {
          const videoSiteId = cacheData.getVideo.organization.site_id;
          const videoLoomOrganizationId = cacheData.getVideo.organization.id;

          if (videoSiteId) {
            // The video belonging to an org associated with an Atlassian site
            return {
              tenantIdType: tenantType.CLOUD_ID,
              tenantId: videoSiteId,
            };
          }

          // The video does not belong to an org associated with an Atlassian site
          return {
            tenantIdType: tenantType.LOOM_ORG_ID,
            tenantId: String(videoLoomOrganizationId),
          };
        }
      } catch (cacheError) {
        // If reading from cache fails, silently continue to fallbacks
        loggerx.debug('No video data found in cache for analytics', {
          videoId: maybeVideoId,
          feature: Feature.AtlassianAnalytics,
        });
      }
    }

    // The page doesn't have a video, or the user doesn't have access to the video they are trying to view
    // track the view based on user auth

    // If we couldn't get video info from cache, fall back to user's tenant
    if (maybeUserSiteId) {
      return {
        tenantIdType: tenantType.CLOUD_ID,
        tenantId: maybeUserSiteId,
      };
    }

    return {
      tenantIdType: tenantType.LOOM_ORG_ID,
      tenantId: String(maybeUserWorkspaceId) || '',
    };
  } catch (error) {
    loggerx.error('Error getting tenant info for analytics', error, {
      feature: Feature.AtlassianAnalytics,
    });
    return undefined;
  }
};

export const getAtlassianAnalyticsClient = (): AnalyticsWebClient => {
  const analyticsClient = init();

  // Only attempt to set user info if we haven't started the process yet
  if (!isSettingUp) {
    isSettingUp = true;

    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    if (!analyticsClient._userInfo.userId) {
      const userInfo = getUserInfo();
      if (!userInfo) {
        loggerx.error('Error getting user info for analytics', undefined, {
          feature: Feature.AtlassianAnalytics,
        });
        return analyticsClient;
      }
      analyticsClient.setUserInfo(userInfo.userIdType, userInfo.userId);
      loggerx.info('Successfully set user info for analytics client', {
        feature: Feature.AtlassianAnalytics,
      });
    }

    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    if (!analyticsClient._tenantInfo.tenantId) {
      const tenantInfo = getTenantInfo();
      if (!tenantInfo) {
        loggerx.error('Error getting tenant info for analytics', undefined, {
          feature: Feature.AtlassianAnalytics,
        });
        return analyticsClient;
      }
      analyticsClient.setTenantInfo(
        tenantInfo.tenantIdType,
        tenantInfo.tenantId
      );
      loggerx.info('Successfully set tenant info for analytics client', {
        feature: Feature.AtlassianAnalytics,
      });
    }
  }

  return analyticsClient;
};
