import cloneDeep from 'lodash/cloneDeep';
import update from 'lodash/update';
import { Paths, Get } from 'type-fest';

// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';
import * as logger from '@js/utilities/loggerx';

import {
  GetCurrentUserSsrDocument,
  GetCurrentUserSsrQuery,
} from '@loomhq/graphql-preload';

import { Feature } from '@loomhq/shared-utilities/constants/product';

import { LoggedInUserResponse } from '../schema/types';

/**
 * @deprecated Use graphql mutations instead of directly writing to the cache. This exists as a legacy bridge to assist in migrating legacy redux actions
 * @param keys A key path in the user object, such as one passed to lodash's _.update
 * @param updateFn A function to update the value at the given key path
 * @returns void
 */
export const updateInCurrentUserCache = <
  Keys extends Paths<GetCurrentUserSsrQuery>,
>(
  keys: Keys,
  updateFn: (
    existingData: Get<GetCurrentUserSsrQuery, Keys>
  ) => Get<LoggedInUserResponse, Keys>
): void => {
  const apolloClient = getGraphQLClient();
  const cacheData: GetCurrentUserSsrQuery | null = apolloClient.readQuery({
    query: GetCurrentUserSsrDocument,
  });

  if (!cacheData) {
    logger.error(
      new Error('tried to write to null user cache'),
      {},
      { feature: Feature.UserApolloCache }
    );

    return;
  }

  // We need to clone the cache data because the result of the cache read restricts updates
  // and silently fails. If we clone and update then it will update correctly.
  const clonedCacheData = cloneDeep(cacheData);
  const updatedUserCache = update(clonedCacheData, keys, updateFn);

  apolloClient.writeQuery({
    query: GetCurrentUserSsrDocument,
    data: updatedUserCache,
  });
};
