const SIDEBAR = 4;
const RESIZER = SIDEBAR + 1;
const EMOJI_PICKER = RESIZER + 1;
const TRANSCRIPT_CORRECTION = RESIZER + 100;

export const Z_INDICES = {
  SIDEBAR,
  RESIZER,
  EMOJI_PICKER,
  TRANSCRIPT_CORRECTION,
};
