// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';
import { useExpUpdatedMobileOnboarding } from '@js/hooks/experiments/useExpUpdatedMobileOnboarding';
import React from 'react';
import * as logger from '@js/utilities/loggerx';

import { Arrange, Container, Spacer, Text } from '@loomhq/lens';

import { Team } from '@loomhq/shared-utilities/constants/product';

import EmptyStateButton from '../EmptyStateButton';
import { EmptyStateType } from '../constants';
import { EMPTY_STATE_CAROUSEL_SPACER_ID } from '../destination-empty-state/constants';
import { MobileDownloadButton } from '../mobile-download-button';
import CommunityCarousel from './CommunityCarousel';
import { COMMUNITY_EMPTY_STATE_CONTENT } from './constants';

import GetCommunityLoomsSortedIdsQuery from './getCommunityLoomIdsForEmptyStates.graphql';
import styles from './styles.module.less';

const CommunityEmptyState = ({
  type,
}: {
  type: EmptyStateType;
}): JSX.Element | null => {
  const { isExpUpdatedMobileOnboarding } = useExpUpdatedMobileOnboarding();

  const { title, subtitle, buttonText } = COMMUNITY_EMPTY_STATE_CONTENT[type];

  const showEmptyStateButton = Boolean(buttonText);

  // TODO: Replace with autogenerated hook
  const { data } = useQuery(GetCommunityLoomsSortedIdsQuery, {
    fetchPolicy: 'no-cache',
    onError: err => {
      logger.error(
        err,
        { message: 'Error loading community content' },
        { team: Team.Outreach }
      );
    },
  });

  const videoIds =
    data?.getCommunityLoomIdsForEmptyStates?.watchSortedAndRandomizedIds;

  const starterVideos = data?.getCommunityLoomIdsForEmptyStates?.starterVideos;

  const alignment = isExpUpdatedMobileOnboarding ? 'left' : 'center';

  return (
    <Container>
      <Arrange justifyContent="center">
        <Container maxWidth="480px">
          <Arrange
            autoFlow="row"
            gap={isExpUpdatedMobileOnboarding ? 'medium' : 1}
          >
            <Text
              alignment={alignment}
              size={isExpUpdatedMobileOnboarding ? 'xlarge' : 'large'}
              fontWeight="bold"
              htmlTag="h2"
            >
              {title}
            </Text>
            <Text
              className={styles.textWithNewline}
              alignment={alignment}
              size={isExpUpdatedMobileOnboarding ? 'medium' : 'large'}
              fontWeight="book"
              color="bodyDimmed"
            >
              {subtitle}
            </Text>
            {isExpUpdatedMobileOnboarding ? null : <Spacer top="medium" />}
            <Arrange
              width="100%"
              justifyContent={
                isExpUpdatedMobileOnboarding ? 'stretch' : 'center'
              }
            >
              {isExpUpdatedMobileOnboarding ? (
                <MobileDownloadButton buttonText={buttonText} />
              ) : showEmptyStateButton ? (
                <EmptyStateButton type={type} isCommunity={true} />
              ) : null}
            </Arrange>
          </Arrange>
        </Container>
      </Arrange>
      <Spacer
        id={EMPTY_STATE_CAROUSEL_SPACER_ID}
        top={isExpUpdatedMobileOnboarding ? 5 : 9}
      />
      {videoIds?.length && starterVideos?.length ? (
        <CommunityCarousel videoIds={videoIds} starterVideos={starterVideos} />
      ) : null}
    </Container>
  );
};

export { EmptyStateType } from '../constants';

// eslint-disable-next-line import/no-default-export
export default CommunityEmptyState;
