import React from 'react';

import { Container, Link, Text } from '@loomhq/lens';
import {
  updateInCurrentUserCache,
  useCurrentUserSelector,
} from '@js/common/current-user';
import { useErrorBar } from '@js/common/error-management/error-bar/useErrorBar';
import { ErrorSeverities } from '@js/constants/error-severities';

// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import { useBannerVisibility } from '../useBannerVisibility';
import { CancelPendingDeletion } from './CancelPendingDeletion.gql';

type DeletionPendingBannerProps = {
  reportBannerVisibility: (component: JSX.Element, isVisible: boolean) => void;
};

export const DeletionPendingBanner = ({
  reportBannerVisibility,
}: DeletionPendingBannerProps): JSX.Element | null => {
  const { showErrorBar } = useErrorBar();
  const isDeletionPending = useCurrentUserSelector(
    user => user.deletionPending,
    false
  );

  const gqlClient = getGraphQLClient();

  const cancelPendingDeletion = async () => {
    try {
      const resp = await gqlClient.mutate({
        mutation: CancelPendingDeletion,
        fetchPolicy: 'no-cache',
      });

      const success = Boolean(resp.data.cancelPendingDeletion?.success);

      if (!success) {
        throw Error('Failed to cancel pending deletion');
      }

      updateInCurrentUserCache(
        'getCurrentUser.user.deletion_pending',
        () => false
      );
      showErrorBar({
        message: "Your account's pending deletion has been canceled.",
        severity: ErrorSeverities.SUCCESS,
      });
    } catch (err) {
      showErrorBar({
        message: 'Oops! Failed to cancel your pending deletion.',
        severity: ErrorSeverities.ERROR,
      });
    }
  };

  const showBanner = isDeletionPending;

  useBannerVisibility(
    showBanner,
    reportBannerVisibility,
    <DeletionPendingBanner reportBannerVisibility={reportBannerVisibility} />
  );

  return showBanner ? (
    <Container
      width="100%"
      backgroundColor="offWhite"
      marginBottom="medium"
      padding="medium"
      radius="medium"
    >
      <Text alignment="center">
        <Text fontWeight="bold" isInline>
          This account will be deleted once your billing cycle is over.
        </Text>{' '}
        <Text isInline>
          {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
          <Link variant="subtle" onClick={() => cancelPendingDeletion()}>
            Undo this action
          </Link>
        </Text>
      </Text>
    </Container>
  ) : null;
};
