import { ErrorSeverities } from '@js/constants/error-severities';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';
import { useErrorBar } from '@js/common/error-management/error-bar/useErrorBar';
import { useVideoPasswordContext } from '@js/common/video-password';
import { useErrorStore } from '@js/components/video-player-fresh/error-layer/ErrorStoreProvider';
import { CommentOrReply } from '@js/pages/share/common/comments/commentOrReply';
import { isReply } from '@js/pages/share/common/comments/isReply';

import RestoreComment from '@js/pages/share/comments/common/data/RestoreComment.gql';

const COMMENT_RESTORE_ERROR = 'Error deleting or restoring comment';

export function useRestoreComment(
  comment: CommentOrReply,
  trackRestoreComment: () => void
): any {
  const { password } = useVideoPasswordContext();
  const { pushError } = useErrorStore();
  const { showErrorBar } = useErrorBar();

  // we do not re-fetch all comments on delete/restore, because we handle the restore placeholder locally
  // TODO: Replace with autogenerated hook
  const [restoreComment] = useMutation(RestoreComment, {
    optimisticResponse: {
      restoreComment: true,
    },
    variables: {
      type: isReply(comment) ? 'REPLY' : 'COMMENT',
      id: comment.id,
      password,
    },
    onError: () => {
      pushError(COMMENT_RESTORE_ERROR);
      showErrorBar({
        message: 'Failed to restore comment.',
        severity: ErrorSeverities.ERROR,
      });
    },
    update: cache => {
      cache.modify({
        id: cache.identify(comment),
        fields: {
          locallyDeleted: () => false,
          deletedAt: () => null,
        },
      });
    },
    onCompleted: () => {
      // analytics tracking
      trackRestoreComment();
    },
  });

  return restoreComment;
}
