// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';

import {
  formatDataAgeLimit,
  FormattedDataAgeLimit,
} from '../helpers/formatDataAgeLimit';

import GetSpaceDataAgeLimit from './GetSpaceDataAgeLimit.graphql';

export const useSpaceDataAgeLimitFormatted = (
  spaceId: string
): FormattedDataAgeLimit | null => {
  // TODO: Replace with autogenerated hook
  const { data } = useQuery(GetSpaceDataAgeLimit, {
    variables: {
      spaceId,
    },
  });

  const dataAgeLimitInSeconds =
    data?.getSpace?.space?.data_age_limit_in_seconds;

  if (dataAgeLimitInSeconds == null) {
    return null;
  }

  return formatDataAgeLimit(dataAgeLimitInSeconds);
};
