import { NAVIGATION_ITEM_CLICKED } from '@js/constants/events';

import { SPACES_BROWSE_PAGE } from '@js/constants/routes';
import { SIDEBAR_SOURCE } from '@js/constants/spaces';

// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client/react';
import { CREATE_SPACE_MODAL } from '@js/common/modal-container';
import { useModals } from '@js/common/modal-container/useModals';
import { useShouldHideLeftNav } from '@js/common/useShouldHideLeftNav';
import { MY_SPACE_MEMBERSHIPS_PAGINATION_LIMIT } from '@js/components/spaces/constants';
import { useGetSpaceLimits } from '@js/hooks/workspace';
import React from 'react';
import { FeatureWrapper } from '@js/utilities/rum/feature-wrapper';
import { ErrorBoundaryTypes } from '@js/utilities/rum/feature-wrapper/constants';
import { useFeatureWrapper } from '@js/utilities/rum/feature-wrapper/context';

import { Icon, TextButton } from '@loomhq/lens';
import { SvgChevronDown } from '@loomhq/lens/icons/chevron-down';
import { SvgSearch } from '@loomhq/lens/icons/search';
import { Feature } from '@loomhq/shared-utilities/constants/product';

import * as analytics from '@js/utilities/analytics';

import GetMySpaceMemberships from '../../../spaces/graphql/GetMySpaceMemberships.graphql';
import MenuLink from '../MenuLink';
import styles from '../styles.module.less';
import Entry from './Entry';

import Title from './Title';

type SpacesProps = {
  isCollapsed: boolean;
  isMobile: boolean;
  navBarIsOpenMobile: boolean;
  showFtuxTooltip?: boolean;
  dismissFtuxOnClick?: () => void;
  setIsLoadingSpaces?: (boolean) => void;
};

const SpacesWithoutFeatureWrapper = ({
  isCollapsed,
  isMobile,
  navBarIsOpenMobile,
  showFtuxTooltip,
  dismissFtuxOnClick,
}: SpacesProps): JSX.Element | null => {
  const { openModal } = useModals();
  const { showBrowseSpaces } = useGetSpaceLimits();

  const { featureLoadedRef } = useFeatureWrapper();

  // TODO: Replace with autogenerated hook
  const { data, fetchMore } = useQuery(GetMySpaceMemberships, {
    variables: { first: MY_SPACE_MEMBERSHIPS_PAGINATION_LIMIT },
    notifyOnNetworkStatusChange: true,
    fetchPolicy: 'cache-and-network',
    nextFetchPolicy: 'cache-first',
  });

  const endCursor = data?.result?.memberships?.pageInfo?.endCursor;
  const hasNextPage = data?.result?.memberships?.pageInfo?.hasNextPage;

  const memberships = data?.result?.memberships?.edges || [];

  const createNewSpace = () => {
    dismissFtuxOnClick && dismissFtuxOnClick();
    openModal({
      modalType: CREATE_SPACE_MODAL,
      options: {
        analyticsSource: SIDEBAR_SOURCE,
      },
    });
    analytics.track(NAVIGATION_ITEM_CLICKED, {
      primary_nav_item: 'space_creation',
    });
  };

  const fetchMoreSpaces = () => {
    fetchMore({
      variables: {
        after: endCursor,
      },
    });
    analytics.track(NAVIGATION_ITEM_CLICKED, {
      primary_nav_item: 'space_fetch_more',
    });
  };

  const hideSideNav = useShouldHideLeftNav();

  return (
    <div ref={featureLoadedRef}>
      <Title
        createNewSpace={createNewSpace}
        isCollapsed={isCollapsed && !hideSideNav}
        isMobile={isMobile}
        navBarIsOpenMobile={navBarIsOpenMobile}
        isFtux={showFtuxTooltip}
      />
      {showBrowseSpaces && (
        <MenuLink
          icon={
            <div className="px:xsmall">
              <Icon size="medium" icon={<SvgSearch />} color="currentColor" />
            </div>
          }
          title="Browse spaces"
          url={SPACES_BROWSE_PAGE}
          collapsed={isCollapsed}
          isMobileCollapsedNav={isMobile && !navBarIsOpenMobile}
          isReactRouterLink
          shouldDim={false}
          onClick={() => {
            analytics.track(NAVIGATION_ITEM_CLICKED, {
              primary_nav_item: 'space_browse',
            });
          }}
        />
      )}

      {memberships.map(membership => (
        <Entry
          key={membership.node.id}
          membership={membership.node}
          isCollapsed={isCollapsed && !hideSideNav}
          isMobile={isMobile}
          navBarIsOpenMobile={navBarIsOpenMobile}
        />
      ))}
      {hasNextPage &&
        (isCollapsed ? (
          <MenuLink
            icon={
              <div className="px:xsmall">
                <Icon
                  size="medium"
                  icon={<SvgChevronDown />}
                  color="currentColor"
                />
              </div>
            }
            title="Show more spaces"
            collapsed={isCollapsed}
            isMobileCollapsedNav={isMobile && !navBarIsOpenMobile}
            isReactRouterLink
            shouldDim={true}
            onClick={fetchMoreSpaces}
          />
        ) : (
          <TextButton
            className={styles.showMoreTextButton}
            size="small"
            icon={<SvgChevronDown />}
            onClick={fetchMoreSpaces}
          >
            Show more
          </TextButton>
        ))}
    </div>
  );
};

export const Spaces = (props: SpacesProps): JSX.Element => {
  return (
    <FeatureWrapper
      feature={Feature.NavigationSpaces}
      errorType={ErrorBoundaryTypes.SILENT}
    >
      <SpacesWithoutFeatureWrapper {...props} />
    </FeatureWrapper>
  );
};
