// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import {
  clearLocalStorageKey,
  getLocalStorageKey,
  setLocalStorageKey,
} from '@js/utilities/localStorage';

import CreateAnonRecordingCache from './CreateAnonRecordingCache.graphql';
import GetVideoInfo from './GetVideoInfo.graphql';
import UpdateAnonRecordingOwnership from './UpdateAnonRecordingOwnership.graphql';

export function slideToElement(className: string): void {
  const element = document.querySelector(`.${className}`);

  if (!element) {
    return;
  }

  window.requestAnimationFrame(() =>
    element.scrollIntoView({ behavior: 'smooth' })
  );
}

export const getVideoInfo = (id: string): Promise<any> => {
  const gqlClient = getGraphQLClient();

  return gqlClient.query({
    query: GetVideoInfo,
    variables: { id },
  });
};

export const createAnonRecordingCache = (
  videoArgs: Record<string, unknown>
): Promise<any> => {
  const gqlClient = getGraphQLClient();

  return gqlClient.mutate({
    mutation: CreateAnonRecordingCache,
    variables: {
      ...videoArgs,
    },
  });
};

export const updateAnonRecordingOwnership = (): Promise<any> => {
  const gqlClient = getGraphQLClient();

  return gqlClient.mutate({
    mutation: UpdateAnonRecordingOwnership,
  });
};

// anon record reply
export const RECORD_REPLY_VIDEO = 'record-reply-video';

export const getRecordedReplyVideoData = (): unknown => {
  return getLocalStorageKey(RECORD_REPLY_VIDEO);
};

export const setRecordedReplyVideoData = (
  data: Record<string, unknown>
): void => {
  setLocalStorageKey(RECORD_REPLY_VIDEO, data);
};

export const removeRecordReplyData = (): void => {
  clearLocalStorageKey(RECORD_REPLY_VIDEO);
};
