import { LoggedInUser } from '@js/common/current-user';
// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import GetUserChecklist from './GetUserChecklist.gql';

interface UserLikeObject {
  first_name?: string | null;
  last_name?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  email?: string;
  aa_is_mastered?: boolean | null;
  aa_id?: string | null;
}

export const getMostCompleteNamePossible = <T extends UserLikeObject>(
  user: T | null
): string => {
  if (!user) {
    return 'User';
  }

  if (user.first_name) {
    if (user.last_name) {
      return user.first_name + ' ' + user.last_name;
    }

    return user.first_name;
  }

  if (user.firstName) {
    if (user.lastName) {
      return user.firstName + ' ' + user.lastName;
    }

    return user.firstName;
  }

  return user?.email ?? '';
};

// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
export const getUserChecklist = () => {
  const gqlClient = getGraphQLClient();

  return gqlClient.query({ query: GetUserChecklist });
};

// TODO(sam): fix this when the user is mapped correctly, currently I believe that the user query from the parent
// isn't correct, and there's a discrepancy between the from `useLoggedInUser` and the raw query from the parent
// that doesn't transform the user properties from the B.E. like the prior query does.
export const isAtlassianMastered = (user: LoggedInUser): boolean =>
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore - see above comment
  Boolean(user?.aaIsMastered) || Boolean(user?.aa_is_mastered);

export const isAtlassianLinked = (user: LoggedInUser): boolean =>
  Boolean(!user.aaIsMastered && user.aaId);

export function logoutUserWithRedirect(redirectUrl?: string): void {
  let logout = '/logout';

  if (redirectUrl) {
    logout += '?redirect_uri=' + encodeURIComponent(redirectUrl);
  }

  window.location.href = logout;
}
