import * as Types from '../../../globalTypes.generated';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {} as const;
export type GetVideoAutoGenInfoQueryVariables = Types.Exact<{
  videoId: Types.Scalars['ID']['input'];
  password?: Types.InputMaybe<Types.Scalars['String']['input']>;
}>;


export type GetVideoAutoGenInfoQuery = { __typename: 'Query', getVideoAutoGenInfo: { __typename: 'GenericError', error: string | null, message: string } | { __typename: 'GetVideoAutoGenInfoPayload', draftId: string | null, isAutoGenerated: boolean } | { __typename: 'InputValidationError', message: string } | { __typename: 'UserNotAuthorizedError', message: string } | null };


export const GetVideoAutoGenInfoDocument = gql`
    query GetVideoAutoGenInfo($videoId: ID!, $password: String) {
  getVideoAutoGenInfo(videoId: $videoId, password: $password) {
    __typename
    ... on GetVideoAutoGenInfoPayload {
      draftId
      isAutoGenerated
    }
    ... on UserNotAuthorizedError {
      message
    }
    ... on GenericError {
      error
      message
    }
    ... on InputValidationError {
      message
    }
  }
}
    `;

/**
 * __useGetVideoAutoGenInfoQuery__
 *
 * To run a query within a React component, call `useGetVideoAutoGenInfoQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetVideoAutoGenInfoQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetVideoAutoGenInfoQuery({
 *   variables: {
 *      videoId: // value for 'videoId'
 *      password: // value for 'password'
 *   },
 * });
 */
export function useGetVideoAutoGenInfoQuery(baseOptions: Apollo.QueryHookOptions<GetVideoAutoGenInfoQuery, GetVideoAutoGenInfoQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<GetVideoAutoGenInfoQuery, GetVideoAutoGenInfoQueryVariables>(GetVideoAutoGenInfoDocument, options);
      }
export function useGetVideoAutoGenInfoLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetVideoAutoGenInfoQuery, GetVideoAutoGenInfoQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<GetVideoAutoGenInfoQuery, GetVideoAutoGenInfoQueryVariables>(GetVideoAutoGenInfoDocument, options);
        }
export type GetVideoAutoGenInfoQueryHookResult = ReturnType<typeof useGetVideoAutoGenInfoQuery>;
export type GetVideoAutoGenInfoLazyQueryHookResult = ReturnType<typeof useGetVideoAutoGenInfoLazyQuery>;
export type GetVideoAutoGenInfoQueryResult = Apollo.QueryResult<GetVideoAutoGenInfoQuery, GetVideoAutoGenInfoQueryVariables>;


// @ts-expect-error Hack to fix a bug in the codegen library: https://github.com/dotansimha/graphql-code-generator/issues/4900#issuecomment-2078402934
type Dummy = Types.Maybe;