// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import { membershipUtils } from '@loomhq/shared-utilities';
import {
  ORG_ROLE_CREATOR,
  ORG_ROLE_CREATOR_LITE,
  ORG_ROLE_VIEWER,
} from '@loomhq/shared-utilities/constants/organizationRoles';
import { WORKSPACE_PLAN_ENTERPRISE } from '@loomhq/shared-utilities/constants/workspacePlans';
import { updateInCurrentUserCache } from '@js/common/current-user';
import { VALIDATE_WORKSPACE_NAME_REGEX } from '@js/constants/regex';

import { MemberRoleWithoutTypeName } from '@js/common/invite-teammates/types';
import { RoleOptions } from '@js/components/manage-workspace/general-settings/types';
import AcceptWorkspaceInviteMutation from './AcceptOrgInvite.gql';
import memberTypeaheadQuery from './MemberTypeaheadQuery.graphql';
import { getUserAvatarThumb } from './avatar';
import updateSelectedWorkspace from './updateSelectedWorkspace.graphql';
import updateUserDefaultWorkspace from './updateUserDefaultWorkspace.graphql';
const { getMemberRoleWithSmallestOrdinality } = membershipUtils;

export const goToWorkspace = async (
  workspaceId: string,
  path = '/team-videos',
  shouldRedirect = true
): Promise<void> => {
  const client = getGraphQLClient();

  await client.mutate({
    mutation: updateSelectedWorkspace,
    variables: { workspaceId },
  });

  if (shouldRedirect) {
    window.location.href = path;
  }
};

export const requestAcceptWorkspaceInvite = async (
  token: string
): Promise<void> => {
  const gqlClient = getGraphQLClient();

  await gqlClient
    .mutate({
      mutation: AcceptWorkspaceInviteMutation,
      variables: {
        token,
      },
    })
    .then(({ data }) => {
      const { accepted } = data;

      return accepted;
    });
};

export const saveDefaultWorkspace = async (
  selectedWorkspaceId: string | undefined
): Promise<void> => {
  const client = getGraphQLClient();

  const { data } = await client.mutate({
    mutation: updateUserDefaultWorkspace,
    variables: { workspaceId: selectedWorkspaceId },
  });

  if (data.updateUserDefaultWorkspace?.success) {
    updateInCurrentUserCache(
      'getCurrentUser.user.default_workspace_id',
      () => selectedWorkspaceId
    );
    return;
  }

  const { message } = data.UpdateDefaultWorkspace;

  throw new Error(message);
};

export const getDefaultRoleForMemberInvitations = ({
  availableRoles,
}: {
  availableRoles: RoleOptions[] | MemberRoleWithoutTypeName[];
}): RoleOptions | MemberRoleWithoutTypeName | undefined => {
  const bestAvailableRole = [
    ORG_ROLE_CREATOR_LITE,
    ORG_ROLE_CREATOR,
    ORG_ROLE_VIEWER,
  ].find(role => availableRoles.some(r => r.value === role));

  return availableRoles.find(r => r.value === bestAvailableRole);
};

export const isValidWorkspaceName = (workspaceName: string): boolean => {
  if (!workspaceName || workspaceName.trim() === '') {
    return true;
  }

  return VALIDATE_WORKSPACE_NAME_REGEX.test(workspaceName);
};

export const getMinimumMembershipRole = ({
  roles,
  hideViewerRole,
}: {
  roles: string[];
  hideViewerRole: boolean;
}): string => {
  let availableRoles = roles;

  if (hideViewerRole) {
    availableRoles = roles.filter(role => role !== ORG_ROLE_VIEWER);
  }

  return getMemberRoleWithSmallestOrdinality(availableRoles);
};

export const isAtlassianManagedWorkspace = (
  workspace: {
    activation_id: string | null;
  } | null
): boolean => Boolean(workspace?.activation_id);

export const isEnterpriseWorkspace = (
  workspace: { type: string | null } | undefined
): boolean => workspace?.type === WORKSPACE_PLAN_ENTERPRISE;

export const searchWorkspaceMembersFn =
  (
    workspaceId: number,
    includeContacts = true
  ): ((query: any, limit?: number) => Promise<any>) =>
  async (query, limit = 10) => {
    const gqlClient = getGraphQLClient();

    const dedup = suggestionList => {
      const alreadyAdded = {};

      return suggestionList.reduce((acc, suggestion) => {
        if (!alreadyAdded[suggestion.email]) {
          alreadyAdded[suggestion.email] = true;

          return [...acc, suggestion];
        }

        return acc;
      }, []);
    };

    const result = await gqlClient.query({
      query: memberTypeaheadQuery,
      variables: {
        workspaceId,
        query,
        limit: limit * 3, // See Loom in PR
        includeContacts,
      },
    });

    const userList = (result.data.searchWorkspaceMembers?.users || [])
      .filter(user => user)
      .map(user => ({
        id: `user:${user.id}`,
        display: user.display_name,
        avatar: getUserAvatarThumb(user.avatars),
        email: user.email,
      }));

    if (!includeContacts) {
      return userList.slice(0, limit);
    }

    const contactList = (result.data.searchWorkspaceContacts?.results || [])
      .filter(contact => contact)
      .map(contact => ({
        id: `workspace_contacts:${contact.id}`,
        display: contact.displayName,
        source: contact.source,
        email: contact.value,
      }));

    return dedup([...userList, ...contactList]).slice(0, limit);
  };
