/* eslint-disable @loomhq/loom/no-js-extension */
// eslint-disable-next-line no-restricted-imports
import { useMutation, useQuery } from '@apollo/client';
import { useIsCurrentUserLoggedIn } from '@js/common/current-user';

import GetMemberProperty from './GetMemberProperty.graphql';
import UpdateMemberProperty from './UpdateMemberProperty.graphql';

export const useMemberProperty = (
  propertyName,
  { onError = () => {}, onCompleted = () => {}, skip = false } = {}
) => {
  const isLoggedIn = useIsCurrentUserLoggedIn();
  const { loading, error, data } = useQuery(GetMemberProperty, {
    skip: !isLoggedIn || skip,
    variables: { name: propertyName },
    onError: err => onError(err),
    onCompleted: data => onCompleted(data?.result?.value),
  });

  return {
    loading,
    error,
    value: data?.result?.value,
  };
};

export const useUpdateMemberProperty = (
  propertyName,
  { onCompleted = null, onError = null, refetchQueries = [] } = {}
) => {
  // TODO: Replace with autogenerated hook
  const [updateMemberProperty, { loading, error }] = useMutation(
    UpdateMemberProperty,
    {
      onCompleted: data => onCompleted && onCompleted(data),
      onError: err => onError && onError(err),
      refetchQueries,
      update: (cache, updatedData) => {
        cache.writeQuery({
          query: GetMemberProperty,
          variables: { name: propertyName },
          data: {
            result: updatedData?.data?.result?.property,
          },
        });
      },
    }
  );

  const boundUpdate = propertyValue => {
    updateMemberProperty({
      variables: {
        name: propertyName,
        value: propertyValue,
      },
    });
  };

  return {
    updateMemberProperty: boundUpdate,
    loading,
    error,
  };
};
