/* eslint-disable no-console */

import { LO_OAUTH as LO_OAUTH_MESSAGE } from '@js/constants/messages';
import { persistAnonActivityDataPreAuth } from '@js/common/auth/login/useLoginHandler';
import { SET_SESSION_STORAGE_IN_OPEN_OAUTH_POPUP } from '@js/constants/metrics';
import {
  LOGIN,
  LOGIN_PAGE,
  LOOM_URI,
  MY_VIDEOS_PAGE,
  WELCOME,
} from '@js/constants/routes';

import url from 'url';

import GetPrimaryAuthTypeForEmail from '@js/common/auth/GetPrimaryAuthTypeForEmail.graphql';
import UpdateUserProperty from '@js/hooks/user/UpdateUserProperty.graphql';
import * as analytics from '@js/utilities/analytics';
import { amplitudeLoaded } from '@js/utilities/analytics/amplitude';
import * as extension from '@js/utilities/extension';
import fetch from '@js/utilities/fetch';
// TODO: Replace with autogenerated hook
import { getGraphQLClient } from '@js/utilities/graphql';
import { jsonParseOrDefault } from '@js/utilities/json/safe-json-parse';
import { getLocation } from '@js/utilities/location';
import * as logger from '@js/utilities/loggerx';
import * as metrics from '@js/utilities/metrics';
import { getParam } from '@js/utilities/url';
import { logoutUserWithRedirect } from '@js/utilities/user';
import { v4 as uuidv4 } from 'uuid';

import { emailUtils, validateUtils } from '@loomhq/shared-utilities';
import { APP_SOURCE_WEBSITE } from '@loomhq/shared-utilities/constants/analytics';
import {
  AUTH_FLOW_TYPES,
  LOOM_OAUTH_POP_UP_SESSION_STORE_KEY,
} from '@loomhq/shared-utilities/constants/auth';
import { WORKOS as WORKOS_AUTH_TYPE } from '@loomhq/shared-utilities/constants/authTypes';
import { HEADER_CONTENT_TYPE } from '@loomhq/shared-utilities/constants/http';
import { JSON as JSON_MIME } from '@loomhq/shared-utilities/constants/mimes';
import { Feature, Team } from '@loomhq/shared-utilities/constants/product';
import { UserPropertyEnum } from '@loomhq/shared-utilities/constants/userProperties';
import { AppSource } from '@loomhq/shared-utilities/types/analytics';
import {
  OAuthData,
  OAuthExtraParams,
  RequestSource,
  AuthFlowType,
} from '@loomhq/shared-utilities/types/auth';

import { requestAcceptInviteLink } from './inviteLink';
import isUnsafeRedirectUrl from './isUnsafeRedirectUrl';
import { requestAcceptWorkspaceInvite } from './workspace';

import type { ApolloQueryResult } from '@apollo/client';
import {
  AuthenticationProviders,
  OAuthPopupKeys,
} from '@loomhq/shared-utilities/constants/authentication';

const { hex } = validateUtils;
const { parseNormalizedLocalAndDomain } = emailUtils;
export * from './auth-anon';

declare global {
  interface Window {
    amplitude: {
      getInstance(instanceName?: string);
    };
  }
}

function isOAuthData(parsedObj: unknown): parsedObj is OAuthData {
  return (
    typeof parsedObj === 'object' &&
    parsedObj !== null &&
    'created' in parsedObj &&
    typeof parsedObj.created === 'boolean' &&
    'error' in parsedObj &&
    (typeof parsedObj.error === 'string' || parsedObj.error === null) &&
    'loginSuccess' in parsedObj &&
    typeof parsedObj.loginSuccess === 'boolean' &&
    'type' in parsedObj &&
    typeof parsedObj.type === 'string' &&
    'userRole' in parsedObj &&
    typeof parsedObj.userRole === 'string' &&
    ('redirect_after' in parsedObj
      ? typeof parsedObj['redirect_after'] === 'string'
      : true)
  );
}

const updateUserProperty = countryCode => {
  const gqlClient = getGraphQLClient();

  gqlClient
    .mutate({
      mutation: UpdateUserProperty,
      variables: {
        name: UserPropertyEnum.SIGNUP_LOCATION,
        value: countryCode,
      },
    })
    .then(({ data }) => {
      const { success } = data;

      return success;
    });
};

const signupLocationCallback = () => {
  try {
    getLocation()
      .then(location => {
        updateUserProperty(location.country);
      })
      .catch(error => {
        logger.warning(error, {
          message: 'Failed to get update location',
          team: Team.Billing,
        });
      });
  } catch (err) {
    logger.warning(err, {
      message: 'Failed to get fetch location',
      team: Team.Billing,
    });
  }
};

// export for testing
// eslint-disable-next-line @loomhq/loom/no-consecutive-uppercase-letters-for-acronyms
export const afterOAuthComplete = async (data: OAuthData): Promise<void> => {
  const deeplink_uri = data.deeplink_uri;
  if (
    data.invalidLogin ||
    (deeplink_uri && isUnsafeRedirectUrl(deeplink_uri))
  ) {
    logoutUserWithRedirect();

    return;
  }

  // eslint-disable-next-line @loomhq/loom/no-consecutive-uppercase-letters-for-acronyms
  let redirectURL;
  const cameFrom = getParam('redirect_after');
  const orgToken = getParam('orgToken') || getParam('orgTokenForMemberPreview');
  const inviteLinkId = getParam('invite_link_id');
  // eslint-disable-next-line @loomhq/loom/no-consecutive-uppercase-letters-for-acronyms
  const companyID = getParam('companyID');
  const redirect = getParam('redirect');

  // This block is for Canny IO SSO redirect
  // companyId and redirect are param Canny gave us, and if both of these are present
  // We stay on the same /login page and let middle 'cannyRedirect' handle the redirect
  // NOTE(tatiana): Removal of the feature flag showed Canny conditional below may not work as we initially thought when writing the test. https://www.loom.com/share/4a335b6d2c194dd98269043fc9a80984

  if (
    companyID &&
    hex(companyID) &&
    redirect &&
    !isUnsafeRedirectUrl(redirect)
  ) {
    window.location.reload();

    return;
  }

  if (!data.loginSuccess) {
    redirectURL = new URL(LOOM_URI + LOGIN_PAGE);
  } else if (data.created) {
    redirectURL = new URL(LOOM_URI + WELCOME);

    try {
      await signupLocationCallback();
    } catch (err) {
      logger.warning(err, {
        message: 'unable to update user location',
        team: Team.Billing,
      });
    }
  } else if (cameFrom) {
    let cameFromDecoded = window.decodeURIComponent(cameFrom);

    if (isUnsafeRedirectUrl(cameFromDecoded)) {
      cameFromDecoded = '/';
    }

    redirectURL = new URL(cameFromDecoded, LOOM_URI);
  } else if (data.redirect_after) {
    // For Google One Tap only
    // When users click on one tap from the share page, they need to stay on the share page
    let cameFromDecoded = window.decodeURIComponent(data.redirect_after);

    if (isUnsafeRedirectUrl(cameFromDecoded)) {
      cameFromDecoded = '/';
    }

    redirectURL = new URL(cameFromDecoded, LOOM_URI);
  } else {
    redirectURL = new URL(LOOM_URI + MY_VIDEOS_PAGE);
  }

  if (data.error != null) {
    redirectURL.searchParams.set('oauth_error', data.error);
  }

  if (orgToken) {
    try {
      await requestAcceptWorkspaceInvite(orgToken);
    } catch (err) {
      logger.error(
        err,
        {
          message: 'Unable to accept invite after oauth',
        },
        { feature: Feature.Authentication }
      );
    }
  } else if (inviteLinkId) {
    try {
      const { success, __typename: responseType } =
        await requestAcceptInviteLink(inviteLinkId, data.created);

      if (responseType === 'GenericError' || !success) {
        logger.warning(
          new Error(
            'InviteLink: Unable to process link after oauth authorization'
          ),
          {
            invite_link_id: inviteLinkId,
            accept_failure_reason: responseType,
          }
        );
      }
    } catch (err) {
      logger.warning(
        err`InviteLink: Unable to process link after oauth authorization`,
        {
          invite_link_id: inviteLinkId,
          error_message: err.message,
        }
      );
    }
  }

  if (data.loginSuccess) {
    extension.signalExtensionLogin(() => {
      /**
       * If deeplink_uri is present, we should redirect to the deeplink_uri and also the
       * redirectURL so the user does not stay stuck on the login page
       */

      if (deeplink_uri) {
        window.location.replace(deeplink_uri);
      }

      window.location.href = redirectURL.toString();
    });
  } else {
    window.location.href = redirectURL.toString();
  }
};

export const login = (
  email: string,
  password: string,
  appSource: AppSource
): Promise<Response> => {
  const { query } = url.parse(window.location.search || '', true);

  const loginUrl = {
    pathname: LOGIN,
    query: {
      app_source: appSource,
      ...query,
    },
  };

  const pathString = url.format(loginUrl);

  return fetch(pathString, {
    method: 'POST',
    headers: { [HEADER_CONTENT_TYPE]: JSON_MIME },
    body: JSON.stringify({ email, password }),
  });
};

export const getPopupMessageCheckHandler = (
  oAuthPopup: Window | null,
  cb: (data: OAuthData) => void,
  removeMessageCheckListener: () => void
) => {
  return (event: MessageEvent): void => {
    try {
      const messageOrigin = new URL(event.origin)?.origin;

      // on the personal settings page and integration tab, it's possible to receive messages from
      // external origins that we are not interested in handling here
      const ignoredOrigins = [`https://js.stripe.com`];
      if (ignoredOrigins.includes(messageOrigin)) {
        return;
      }

      // OAuth messages are always strings. If we receive a non-string, we ignore it.
      // Object messages are sometimes received from other sources such as the chrome extension.
      if (typeof event.data !== 'string') {
        return;
      }

      const defaultData = {
        type: 'default-oauth-type',
      };

      const data = jsonParseOrDefault<OAuthData>(
        event.data,
        defaultData,
        isOAuthData
      );

      if (data.type === 'default-oauth-type') {
        logger.warning(
          Error('Malformed auth data, falling back to default oauth type'),
          { event },
          { team: Team.Outreach }
        );
      }

      // TODO: in which cases would we actually want a message from another origin intercepted
      // in this event handler to be considered an "invalidLogin" and close this popup and
      // remove the listener? this seems to only be referenced in the default callback above
      // (+afterOAuthComplete+). if we can remove this behavior to essentially ignore such
      // events, instead of checking for +ignoredOrigins+ above, we could just return early if
      // this if clause is true
      if (messageOrigin !== LOOM_URI || data.type !== LO_OAUTH_MESSAGE) {
        data.invalidLogin = true;
      }

      removeMessageCheckListener();
      oAuthPopup?.close();

      cb(data);
    } catch (err) {
      logger.error(
        'Auth Error',
        {
          message: err.message,
          origin: event.origin,
          event,
        },
        { feature: Feature.Authentication, team: Team.Outreach }
      );

      return;
    }
  };
};

// Exported for testing
// eslint-disable-next-line @loomhq/loom/no-consecutive-uppercase-letters-for-acronyms
export const createOAuthUrl = (
  urlRoot: string,
  provider: string,
  extraParams: OAuthExtraParams = {},
  authFlowType: AuthFlowType,
  anonID: string,
  deviceId?: string
): string => {
  const baseUrl = new URL(`${urlRoot}/api/auth/${provider}`);
  const baseParams = new URLSearchParams(baseUrl.search);

  Object.keys(extraParams).map(k => baseParams.set(k, extraParams[k]));

  const app_source = getParam('app_source') || APP_SOURCE_WEBSITE;
  baseParams.set('app_source', app_source);
  baseParams.set('auth_flow_type', authFlowType);
  baseParams.set('anon_id', anonID);

  if (deviceId) {
    baseParams.set('device_id', deviceId);
  }

  const completeUrl = `${baseUrl.toString()}?${baseParams.toString()}`;

  return completeUrl;
};

// eslint-disable-next-line @loomhq/loom/no-consecutive-uppercase-letters-for-acronyms
export const openOAuthPopup = (
  provider: OAuthPopupKeys,
  extraParams: OAuthExtraParams = {},
  cb: (data: OAuthData) => void = afterOAuthComplete
): void => {
  analytics.ready(() => {
    const { anonID } = analytics.getAnalyticsIds();

    const deviceId = amplitudeLoaded()
      ? window.amplitude.getInstance().options.deviceId
      : undefined;

    const completeUrl = createOAuthUrl(
      LOOM_URI,
      provider,
      extraParams,
      AUTH_FLOW_TYPES.POPUP,
      anonID,
      deviceId
    );
    if (extraParams?.anonActivityData) {
      persistAnonActivityDataPreAuth(extraParams.anonActivityData);
    }
    const shouldSkipPopup = extraParams.email
      ? skipPopupOauth(provider, extraParams.email)
      : false;

    if (shouldSkipPopup) {
      window.location.href = completeUrl;
      return;
    }
    if (window.sessionStorage) {
      sessionStorage.setItem(
        LOOM_OAUTH_POP_UP_SESSION_STORE_KEY,
        JSON.stringify(true)
      );
      metrics.incrementMetric(SET_SESSION_STORAGE_IN_OPEN_OAUTH_POPUP, {
        status: 'success',
      });
    } else {
      metrics.incrementMetric(SET_SESSION_STORAGE_IN_OPEN_OAUTH_POPUP, {
        status: 'failure',
      });
    }

    const oAuthPopup = window.open(
      completeUrl,
      `loom_${uuidv4()}_popup`,
      'width=600,height=800'
    );

    const removeMessageCheckListener = () => {
      window.removeEventListener('message', messageCheck);
    };

    const messageCheck = getPopupMessageCheckHandler(
      oAuthPopup,
      cb,
      removeMessageCheckListener
    );

    window.addEventListener('message', messageCheck);

    // Check if popup is closed manually and clean up event listener
    if (oAuthPopup) {
      const handleParentFocus = () => {
        if (oAuthPopup.closed) {
          window.removeEventListener('focus', handleParentFocus);
          removeMessageCheckListener();
        }
      };
      window.addEventListener('focus', handleParentFocus);
    }
  });
};

// eslint-disable-next-line @loomhq/loom/no-consecutive-uppercase-letters-for-acronyms
export const openOAuthInMainWindow = (
  provider: AuthenticationProviders,
  extraParams: OAuthExtraParams = {}
): void => {
  analytics.ready(() => {
    const { anonID } = analytics.getAnalyticsIds();
    if (extraParams?.anonActivityData) {
      persistAnonActivityDataPreAuth(extraParams.anonActivityData);
    }
    const deviceId = amplitudeLoaded()
      ? window.amplitude.getInstance().options.deviceId
      : undefined;

    const oAuthUrl = createOAuthUrl(
      LOOM_URI,
      provider,
      extraParams,
      AUTH_FLOW_TYPES.MAIN_WINDOW,
      anonID,
      deviceId
    );

    window.location.href = oAuthUrl;
  });
};

/* Temporary solution till we roll out deprecating oAuth popups*/
export const skipPopupOauth = (provider: string, email: string): boolean => {
  try {
    const [_, domain] = parseNormalizedLocalAndDomain(
      decodeURIComponent(email)
    );
    if (provider === WORKOS_AUTH_TYPE && domain === 'onevisionresources.com') {
      return true;
    }
    return false;
  } catch (err) {
    return false;
  }
};

export const getPrimaryAuthTypeForEmail = (
  email: string | object,
  requestSource?: RequestSource
): Promise<
  ApolloQueryResult<{
    response: { __typename: string; authType: string; redirectUri?: string };
  }>
> => {
  const client = getGraphQLClient();

  return client.query({
    query: GetPrimaryAuthTypeForEmail,
    variables: { email, requestSource },
    fetchPolicy: 'no-cache',
  });
};

const DESKTOP = 'desktop';

// eslint-disable-next-line @loomhq/loom/no-consecutive-uppercase-letters-for-acronyms
export const shouldRenderOAuthResult = (
  loginType: string,
  redirect: string
): boolean => {
  if (loginType === WORKOS_AUTH_TYPE) {
    return false;
  } else if (redirect && !isUnsafeRedirectUrl(redirect)) {
    // When arriving here from shared auth init from Desktop we do want to render.
    return loginType.includes(DESKTOP);
  }

  return true;
};
