/* eslint-disable @loomhq/loom/no-js-extension */
// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import AcceptInviteLinkInvitation from './AcceptInviteLinkInvitation.gql';

export const requestAcceptInviteLink = async (inviteLinkId, isNewUser) => {
  const client = getGraphQLClient();

  const {
    data: { acceptInviteLinkInvitation: result },
  } = await client.mutate({
    mutation: AcceptInviteLinkInvitation,
    variables: { inviteLinkId, isNewUser },
  });

  return result;
};
