import { ENTERED_VARIABLES_PAGE } from '@js/constants/events';
import { LOOM_URI, VIDEOS_LOOMS_PAGE } from '@js/constants/routes';

import { getWordWithoutPossessive } from '@js/pages/edit-video/common/getWordWithoutPossessive';
import { VariableKey } from '@js/pages/edit-video/page/transcript-editor/common/state/common/types';

// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import {
  EDIT_PAGE_VARIABLES_MODE,
  VARIABLES_VIDEOS_CREATED_SOURCE_PARAM,
} from '@loomhq/shared-utilities/constants/urlParams';
import { getSlug } from '@loomhq/shared-utilities/utilities/folderUtils';
import { VideoPersonalizationType } from '@js/globalTypes.generated';
import { track } from '@js/utilities/analytics';

import { readCsvFile } from '@js/utilities/file';

import { cleanTranscriptWord } from '../../helpers/variables';
import { MAX_SELECTED_TOKENS } from './constants';
import {
  AudioVariableFromTaskFragment,
  AudioVariableFromTaskFragmentDoc,
  TaskStatusFragment,
  TaskStatusFragmentDoc,
} from './taskStatus.generated';
import { AudioVariablePreviewData } from './types';

import type { TtsVideosFolderFragment } from './tts.generated';
import {
  TokenDict,
  DecoratedToken,
} from '@js/pages/edit-video/page/transcript-editor/common/types';

export const redirectToVariablesEditPage = (
  videoId: string,
  source: string
): void => {
  const videoUrl = `${LOOM_URI}/edit/${videoId}?${EDIT_PAGE_VARIABLES_MODE}=true`;
  track(ENTERED_VARIABLES_PAGE, {
    source,
    video_id: videoId,
  });
  window.location.href = videoUrl;
};

export const redirectToFolderPageFromAudioVariablesPage = (
  folder: TtsVideosFolderFragment
): void => {
  window.location.href = `${LOOM_URI}${VIDEOS_LOOMS_PAGE}/${getSlug(
    folder
  )}?${VARIABLES_VIDEOS_CREATED_SOURCE_PARAM}=${
    VideoPersonalizationType.Audio
  }`;
};

export const getAllInstancesOfKey = ({
  selectedKeys,
  transcriptTokens,
  wordToTokens,
  deletedTokens,
}: {
  selectedKeys: VariableKey[];
  transcriptTokens: TokenDict;
  wordToTokens: Map<string, DecoratedToken[]>;
  deletedTokens: TokenDict;
}): {
  variableKeys: VariableKey[];
} => {
  // If multi-select, we do not support multi-instance, return.
  if (
    selectedKeys.length > 1 ||
    selectedKeys.some(key => key.keysInRange.length > 1)
  ) {
    return { variableKeys: [...selectedKeys] };
  }

  const selectedTokenKey = selectedKeys[0].startKey;
  const selectedToken = transcriptTokens[selectedTokenKey];
  const selectedWord = cleanTranscriptWord(selectedToken.value);

  const tokensForWord = wordToTokens.get(selectedWord);

  // If <=1 instance of word within transcript, no multi-instance possible, return.
  if (!tokensForWord || tokensForWord.length <= 1) {
    return { variableKeys: [...selectedKeys] };
  }

  const deletedTokenKeys = new Set(Object.keys(deletedTokens));
  const variableKeys: VariableKey[] = [];

  for (const token of tokensForWord) {
    const isTokenTrimmed = deletedTokenKeys.has(token.key);

    // don't add trimmed tokens
    if (isTokenTrimmed) {
      continue;
    }

    variableKeys.push({
      startKey: token.key,
      endKey: token.key,
      keysInRange: [token.key],
    });
  }

  return { variableKeys };
};

export const ensureKeysTimestampsAreWithinPreviewRanges = ({
  audioVariables,
  timestampsForKeys,
}: {
  audioVariables: AudioVariablePreviewData[];
  timestampsForKeys: { startTsInSecs: number; endTsInSecs: number }[];
}): boolean => {
  const sortedRanges = audioVariables
    .map(audioVariable => {
      return {
        start: audioVariable.startTimestamp,
        end: audioVariable.endTimestamp,
      };
    })
    .sort((a, b) => a.start - b.start);

  const sortedTimestamps = timestampsForKeys.sort(
    (a, b) => a.startTsInSecs - b.startTsInSecs
  );

  for (const timestamp of sortedTimestamps) {
    const isRangeCovered = sortedRanges.some(
      range =>
        timestamp.startTsInSecs >= range.start &&
        timestamp.endTsInSecs <= range.end
    );

    if (!isRangeCovered) {
      return false;
    }
  }

  return true;
};

export const getAudioVariableFromCache = (
  audioVariableId: string
): AudioVariablePreviewData => {
  const cache = getGraphQLClient().cache;

  const audioVariable: AudioVariableFromTaskFragment | null =
    cache.readFragment({
      id: cache.identify({
        id: audioVariableId,
        __typename: 'AudioVariable',
      }),
      fragment: AudioVariableFromTaskFragmentDoc,
    });

  if (!audioVariable) {
    throw new Error('Could not find audioVariable in apollo cache.');
  }

  const taskStatus: TaskStatusFragment | null = cache.readFragment({
    id: cache.identify({
      id: audioVariable.taskId,
      __typename: 'TaskStatusPayload',
    }),
    fragment: TaskStatusFragmentDoc,
  });

  return {
    id: audioVariable.id,
    status: taskStatus?.status ?? 'sent',
    startTimestamp: audioVariable.startTsInOriginalForSentence ?? 0,
    endTimestamp: audioVariable.endTsInOriginalForSentence ?? 0,
  };
};

export const getStringFromVariableKeys = ({
  variableKeys,
  transcriptTokens,
}: {
  variableKeys: VariableKey[];
  transcriptTokens: TokenDict;
}): { stringFromVariableKeys: string; isSelectionOverLimit: boolean } => {
  const keysInRange = variableKeys[0] ? variableKeys[0].keysInRange : [];
  const variableKeysAsSet = new Set(keysInRange);

  if (keysInRange.length === 1) {
    const stringFromVariableKeys = getWordWithoutPossessive(
      transcriptTokens[keysInRange[0]].value
    );

    return { stringFromVariableKeys, isSelectionOverLimit: false };
  }

  let stringFromVariableKeys = keysInRange
    .slice(0, MAX_SELECTED_TOKENS + 1)
    .map(variableKey => transcriptTokens[variableKey].value)
    .join('');

  if (variableKeysAsSet.size > MAX_SELECTED_TOKENS) {
    stringFromVariableKeys += '...';
  }

  const isSelectionOverLimit = variableKeysAsSet.size > MAX_SELECTED_TOKENS;

  return { stringFromVariableKeys, isSelectionOverLimit };
};

export const findDuplicateIndicesFromRows = (
  importedRows: { name: string; email: string }[],
  existingRows: { name: string; email: string }[]
): Set<number> => {
  const seenEmails = new Set<string>();
  const duplicates = new Set<number>();
  existingRows.forEach(row => {
    if (row.email === '') {
      return;
    }
    seenEmails.add(row.email);
  });
  importedRows.forEach((row, index) => {
    if (row.email === '') {
      return;
    }
    if (seenEmails.has(row.email)) {
      duplicates.add(index);
    } else {
      seenEmails.add(row.email);
    }
  });
  return duplicates;
};

export const handleImportFile = async (
  file: File
): Promise<{ name: string; email: string }[]> => {
  const uploadedRows: Array<string[]> | undefined | null =
    await readCsvFile(file);

  if (!uploadedRows || uploadedRows.length === 0) {
    throw new Error('The uploaded file is empty.');
  }

  const firstRow = uploadedRows.shift();

  if (!firstRow || !firstRow.includes('name')) {
    throw new Error('The uploaded file must have a column labeled “name”.');
  }

  const nameIndex = firstRow.indexOf('name');
  const emailIndex = firstRow.indexOf('email');
  const importedRows: { name: string; email: string }[] = [];

  uploadedRows.forEach(uploadedRow => {
    const name = uploadedRow[nameIndex];
    const email = emailIndex !== -1 ? uploadedRow[emailIndex] : '';
    importedRows.push({ name, email });
  });

  return importedRows;
};
