/* eslint-disable @loomhq/loom/no-js-extension */
import { PROFILE_FOLLOWS_BUTTON_CLICKED } from '@js/constants/events';

// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';
import { SHOW_FOLLOWS_MODAL } from '@js/common/modal-container';
import { useModals } from '@js/common/modal-container/useModals';
import pluralize from 'pluralize';
import React from 'react';

import { Spacer, TextButton, Text } from '@loomhq/lens';
import { FollowStreamType } from '@loomhq/shared-utilities/constants/follows';
import * as analytics from '@js/utilities/analytics';

import GetUserFollowsCount from './GetUserFollowsCount.graphql';
import styles from './styles.module.css';

import { AnalyticsEntityId } from '@loomhq/shared-utilities/utilities/analytics/analyticUtils';
import { withIdentifiers } from '../../../../utilities/analytics/attribute-transformer';

// eslint-disable-next-line import/no-default-export
export default function StreamCountHeader(props) {
  const { profileId, firstName, lastName, loggedInUser, isMobile } = props;
  // TODO: Replace with autogenerated hook
  const { data, loading } = useQuery(GetUserFollowsCount, {
    variables: {
      profileId,
    },
    fetchPolicy: 'cache-and-network',
    nextFetchPolicy: 'cache-first',
  });
  const followerCount = data?.result?.followerCount;
  const followingCount = data?.result?.followingCount;
  const streamType = data?.result?.streamType;

  const { openModal } = useModals();

  if (loading) {
    return <></>;
  }

  if (!streamType) {
    return <></>;
  }

  const showFollowsModal = activeTab => {
    analytics.track(PROFILE_FOLLOWS_BUTTON_CLICKED, {
      ...withIdentifiers(
        PROFILE_FOLLOWS_BUTTON_CLICKED,
        AnalyticsEntityId.user(profileId, 'profileId')
      ),
      button: activeTab === 1 ? 'followers' : 'following',
    });

    openModal({
      modalType: SHOW_FOLLOWS_MODAL,
      options: {
        firstName,
        lastName,
        profileId,
        loggedInUser,
        activeTab,
      },
    });
  };

  return (
    <>
      {streamType === FollowStreamType.USER_PROFILE ? (
        <ul className="flex">
          <li>
            <TextButton
              size={isMobile ? 'small' : 'medium'}
              onClick={() => showFollowsModal(1)}
            >
              {followerCount || 0} {pluralize('Followers', followerCount || 0)}
            </TextButton>
          </li>

          <li>
            <TextButton
              size={isMobile ? 'small' : 'medium'}
              onClick={() => showFollowsModal(2)}
            >
              {followingCount || 0} Following
            </TextButton>
          </li>
        </ul>
      ) : (
        <ul className="flex">
          <li>
            <Text
              size={isMobile ? 'small' : 'medium'}
              fontWeight="bold"
              className={styles.textCounts}
            >
              {followerCount || 0} {pluralize('Followers', followerCount || 0)}
            </Text>
          </li>
          <li>
            <Text size={isMobile ? 'small' : 'medium'} fontWeight="bold">
              {followingCount || 0} Following
            </Text>
          </li>
        </ul>
      )}

      <Spacer right={1} />
    </>
  );
}
