import { ErrorSeverities } from '@js/constants/error-severities';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';
import { useErrorBar } from '@js/common/error-management/error-bar/useErrorBar';
import { useVideoPasswordContext } from '@js/common/video-password';
import { useErrorStore } from '@js/components/video-player-fresh/error-layer/ErrorStoreProvider';
import { CommentOrReply } from '@js/pages/share/common/comments/commentOrReply';
import { isReply } from '@js/pages/share/common/comments/isReply';

import DeleteComment from './DeleteComment.gql';

const COMMENT_DELETE_ERROR = 'Error deleting comment';

export function useDeleteComment(
  comment: CommentOrReply,
  onCompleted: () => void,
  onUpdate?: () => void
): any {
  const { password } = useVideoPasswordContext();
  const { pushError } = useErrorStore();
  const { showErrorBar } = useErrorBar();

  // we do not re-fetch all comments on delete/restore, because we handle the restore placeholder locally
  // TODO: Replace with autogenerated hook
  const [deleteComment] = useMutation(DeleteComment, {
    optimisticResponse: {
      deleteComment: true,
    },
    variables: {
      type: isReply(comment) ? 'REPLY' : 'COMMENT',
      id: comment.id,
      password,
    },
    onError: () => {
      pushError(COMMENT_DELETE_ERROR);
      showErrorBar({
        message: 'Failed to delete comment.',
        severity: ErrorSeverities.ERROR,
      });
    },
    update: cache => {
      cache.modify({
        id: cache.identify(comment),
        fields: {
          locallyDeleted: () => true,
          deletedAt: () => new Date(), // fill with current date until it is updated in db
        },
      });

      if (onUpdate) {
        onUpdate();
      }
    },
    onCompleted: () => {
      onCompleted();
    },
  });

  return deleteComment;
}
