/* eslint-disable @loomhq/loom/no-js-extension */
// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';
import { useEffect } from 'react';

import TagClickedMutation from './TagClickedMutation.graphql';
import TagViewedMutation from './TagViewedMutation.graphql';

export function useLogTagClickedMutation() {
  // TODO: Replace with autogenerated hook
  const [logTagClicked] = useMutation(TagClickedMutation);

  return logTagClicked;
}

export function useLogTagViewed(tagName) {
  // TODO: Replace with autogenerated hook
  const [logTagViewed] = useMutation(TagViewedMutation);

  useEffect(() => {
    logTagViewed({
      variables: {
        tag: tagName,
      },
    });
  }, [logTagViewed, tagName]);
}
