import {
  SIDEBAR_FOLLOWED_PROFILE_CLICKED,
  SIDEBAR_FOLLOWED_TAG_CLICKED,
} from '@js/constants/events';

// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';

import UserAvatar from '@js/components/user-avatar';
import React, { FC } from 'react';

import { getUserAvatarThumb } from '@js/utilities/avatar';

import { FeatureWrapper } from '@js/utilities/rum/feature-wrapper';
import { ErrorBoundaryTypes } from '@js/utilities/rum/feature-wrapper/constants';
import { useFeatureWrapper } from '@js/utilities/rum/feature-wrapper/context';
import { getMostCompleteNamePossible } from '@js/utilities/user';

import { Align, Container, Spacer, Text } from '@loomhq/lens';

import { Feature } from '@loomhq/shared-utilities/constants/product';
import GetUserFollowedStreams from '@js/common/follows/GetUserFollowedStreams.graphql';
import * as analytics from '@js/utilities/analytics';

import MenuLink from '../../../components/layout/navigation/MenuLink';
import styles from '../../../components/layout/navigation/styles.module.less';
import { SuggestedFollows } from '../../../components/layout/navigation/suggested-follows';
import { useLogTagClickedMutation } from '../../../components/tags/tag-events';

import { AnalyticsEntityId } from '@loomhq/shared-utilities/utilities/analytics/analyticUtils';
import { withIdentifiers } from '../../../utilities/analytics/attribute-transformer';

const FollowsSectionWithoutFeatureWrapper = ({
  isCollapsed,
  isMobile,
  navBarIsOpenMobile,
}) => {
  const logTagClicked = useLogTagClickedMutation();

  // TODO: Replace with autogenerated hook
  const { loading: followsLoading, data: follows } = useQuery(
    GetUserFollowedStreams,
    {
      notifyOnNetworkStatusChange: true,
      fetchPolicy: 'no-cache',
    }
  );

  const { featureLoadedRef } = useFeatureWrapper();

  // TODO: Please refactor this to not be a nested component
  // eslint-disable-next-line react/no-unstable-nested-components
  const ProfileLink = ({ profile, ...props }) => {
    const name = getMostCompleteNamePossible(profile.user);

    return (
      <MenuLink
        icon={
          <UserAvatar
            avatarSrc={getUserAvatarThumb(profile.user.avatars)}
            name={name}
            alt={name}
            avatarSize={3}
          />
        }
        title={name}
        url={`/profile/${profile.user.profile?.profileUrl}`}
        collapsed={isCollapsed}
        isMobileCollapsedNav={isMobile && !navBarIsOpenMobile}
        isReactRouterLink
        shouldDim={!profile.unread}
        onClick={() => {
          analytics.track(
            SIDEBAR_FOLLOWED_PROFILE_CLICKED,
            withIdentifiers(
              SIDEBAR_FOLLOWED_PROFILE_CLICKED,
              AnalyticsEntityId.user(profile.id, 'profileUserId')
            )
          );
        }}
        {...props}
      />
    );
  };

  // TODO: Please refactor this to not be a nested component
  // eslint-disable-next-line react/no-unstable-nested-components
  const TagLink = ({ tag, ...props }) => (
    <MenuLink
      icon={
        <Container width="1.5rem">
          <Align alignment="center">
            <Text fontWeight="bold">#</Text>
          </Align>
        </Container>
      }
      title={tag.name}
      url={`/tag/${tag.name}`}
      collapsed={isCollapsed}
      isMobileCollapsedNav={isMobile && !navBarIsOpenMobile}
      isReactRouterLink
      shouldDim={!tag.unread}
      onClick={() => {
        logTagClicked({
          variables: {
            tag: tag.name,
            context: 'FollowSidebar',
          },
        });
        analytics.track(
          SIDEBAR_FOLLOWED_TAG_CLICKED,
          withIdentifiers(
            SIDEBAR_FOLLOWED_TAG_CLICKED,
            AnalyticsEntityId.tag(tag.id, 'tagId')
          )
        );
      }}
      {...props}
    />
  );

  if (followsLoading && !follows?.result) {
    return null;
  }

  const followedProfiles = follows?.result?.profiles || [];
  const followedTags = follows?.result?.tags || [];

  return (
    <>
      {(followedProfiles.length > 0 || followedTags.length > 0) && (
        <>
          <div className={styles.librariesHeading} ref={featureLoadedRef}>
            <Spacer bottom="small" left="xsmall">
              <Text fontWeight="bold" color="bodyDimmed">
                Following
              </Text>
            </Spacer>
          </div>

          {followedProfiles.map(profile => (
            <ProfileLink key={profile.user.id} profile={profile} />
          ))}

          {followedTags.map(tag => (
            <TagLink key={tag.name} tag={tag} />
          ))}
        </>
      )}

      {(followedProfiles.length > 0 || followedTags.length > 0) && (
        <Spacer top="medium" />
      )}

      <SuggestedFollows
        followedProfiles={followedProfiles}
        followedTags={followedTags}
        ProfileLink={ProfileLink}
        TagLink={TagLink}
      />
    </>
  );
};

interface FollowsSectionProps {
  isCollapsed: boolean;
  isMobile: boolean;
  navBarIsOpenMobile: boolean;
}

export const FollowsSection: FC<
  React.PropsWithChildren<FollowsSectionProps>
> = ({ isCollapsed, isMobile, navBarIsOpenMobile }: FollowsSectionProps) => {
  return (
    <FeatureWrapper
      feature={Feature.NavigationFollowing}
      errorType={ErrorBoundaryTypes.SILENT}
    >
      <FollowsSectionWithoutFeatureWrapper
        isCollapsed={isCollapsed}
        isMobile={isMobile}
        navBarIsOpenMobile={navBarIsOpenMobile}
      />
    </FeatureWrapper>
  );
};
