/* eslint-disable @loomhq/loom/no-js-extension */
// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';
import { useCurrentUserSelector } from '@js/common/current-user';
import { useMemo } from 'react';

import GetSuggestedStreams from './GetSuggestedStreams.graphql';

export function useSuggestedFollows({
  followedProfileIds,
  followedTagNames,
  skip,
}) {
  const userId = useCurrentUserSelector(user => user.id, undefined);
  // TODO: Replace with autogenerated hook
  const { data: suggestedFollows } = useQuery(GetSuggestedStreams, {
    notifyOnNetworkStatusChange: true,
    fetchPolicy: 'no-cache',
    skip,
  });

  const { suggestedProfiles, suggestedTags } = useMemo(() => {
    if (!suggestedFollows?.result) {
      return { suggestedProfiles: [], suggestedTags: [] };
    }

    // Filter out duplicates
    const suggestedProfiles =
      followedProfileIds?.size > 0
        ? suggestedFollows.result.profiles.filter(
            profile =>
              !followedProfileIds.has(profile.user.id) &&
              String(userId) !== profile.user.id
          )
        : [];
    // Filter out duplicates
    const suggestedTags =
      followedTagNames?.length > 0
        ? suggestedFollows.result.tags.filter(
            tag => !followedTagNames.has(tag.name)
          )
        : [];

    return {
      suggestedProfiles,
      suggestedTags,
    };
  }, [suggestedFollows?.result, followedProfileIds, followedTagNames, userId]);

  return {
    suggestedProfiles,
    suggestedTags,
  };
}
