import { EMOJI_REACTION_DELETED } from '@js/constants/events';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';

import { useAnonUserName } from '@js/common/useAnonUserName';
import { useVideoPasswordContext } from '@js/common/video-password';

import {
  uid,
  DeleteReactionPayload,
  NewReactionPayload,
  useVideoContext,
  AUTO_REACTION_HANDS_ID,
  AUTO_REACTION_PARTY_ID,
} from '@js/common/video-player';

import { useDeleteAutoReaction } from '@js/pages/share/comments/common/auto-comment-and-reaction/hooks';

import { useMemo } from 'react';

import * as logger from '@js/utilities/loggerx';

import { trimmingUtils } from '@loomhq/shared-utilities';
import {
  EMOJI_STRING_TO_KEY,
  getReactionType,
} from '@loomhq/shared-utilities/constants/emojiReactions';
import { Feature } from '@loomhq/shared-utilities/constants/product';
import { track } from '@js/utilities/analytics';

import { useErrorStore } from '../error-layer/ErrorStoreProvider';
import { GraphQlReactionFromServer, TrimRange } from '../utils';
import CreateReaction from './CreateReaction.gql';

import { useDeleteVideoReactionMutation } from './DeleteReaction.generated';
import { useFetchVideoReactionsQuery } from './FetchReactions.generated';
import FetchReactions from './FetchReactions.gql';

const REACTION_CREATE_ERROR = 'Error creating reaction';

const { convertTrimTimeToFullTime } = trimmingUtils;

const REACTION_FETCH_ERROR = 'Error fetching reactions';
const DELETE_REACTION_ERROR = 'Error deleting reaction';

export function useFetchReactions(): GraphQlReactionFromServer[] {
  const { video } = useVideoContext();
  const { password } = useVideoPasswordContext();
  const { pushError } = useErrorStore();

  const skipFetch = !video?.modelId || !video.reactionsEnabled;

  const { data } = useFetchVideoReactionsQuery({
    variables: { id: video.modelId, password },
    skip: skipFetch,
    onError: () => pushError(REACTION_FETCH_ERROR),
  });

  const filteredReactions = useMemo(() => {
    if (
      !data ||
      !data.videoReactionsForVideo ||
      data.videoReactionsForVideo.__typename !== 'VideoReactionsSuccessPayload'
    ) {
      return [];
    }

    const reactions = data.videoReactionsForVideo.reactions ?? [];

    return reactions.map(r => {
      return {
        id: r.id,
        time: r.time,
        reaction: r.reaction,
        extended_reaction: r.extended_reaction || null,
        anon_user_id: r.anon_user_id || undefined,
        anon_user_name: r.anon_user_name || undefined,
        locallyCreated: r.locallyCreated || undefined,
        localId: r.localId || undefined,
        user: r.user
          ? {
              id: r.user.id,
              display_name: r.user.display_name,
            }
          : undefined,
      };
    });
  }, [data]);

  return filteredReactions;
}

export function useCreateReaction(): (payload: NewReactionPayload) => void {
  const { video } = useVideoContext();
  const { password } = useVideoPasswordContext();
  const { pushError } = useErrorStore();
  const { anonUserName } = useAnonUserName();
  const trimRanges: TrimRange[] = video.processingInformation?.trimRanges || [];

  // TODO: Replace with autogenerated hook
  const [createReactionInternal] = useMutation(CreateReaction);

  const createReaction = (payload: NewReactionPayload) => {
    const { type, time } = payload;

    const reactionType = getReactionType(type as string);

    const adjustedTime = Math.round(
      convertTrimTimeToFullTime(Math.round(time * 1000), trimRanges)
    );
    const localId = uid();

    createReactionInternal({
      variables: {
        videoId: video.modelId,
        password,
        time: adjustedTime,
        type,
        userName: anonUserName,
        reactionType,
      },
      onError: err => {
        pushError(REACTION_CREATE_ERROR);
        logger.error(
          err,
          {
            message: REACTION_CREATE_ERROR,
            error: err,
          },
          { feature: Feature.VideoReactions }
        );
      },
      update: (cache, data) => {
        const newlyCreatedReaction = data.data.addVideoReaction;

        cache.updateQuery(
          {
            query: FetchReactions,
            variables: { id: video.modelId, password },
          },
          cacheData => {
            // cacheData can be null
            if (cacheData) {
              const currentReactions =
                cacheData.videoReactionsForVideo.reactions;

              return {
                videoReactionsForVideo: {
                  __typename: 'VideoReactionsSuccessPayload',
                  reactions: [
                    ...currentReactions,
                    { ...newlyCreatedReaction, locallyCreated: true, localId },
                  ],
                },
              };
            }
          }
        );
      },
      optimisticResponse: {
        addVideoReaction: {
          __typename: 'PublicVideoReaction',
          reaction: EMOJI_STRING_TO_KEY[type as string] || 1,
          extended_reaction: (type as string) || null,
          time: adjustedTime,
          anon_user_id: null,
          anon_user_name: null,
          user: {
            id: 'Loading',
            display_name: '',
          },
          id: localId,
        },
      },
    });
  };

  return createReaction;
}

export function useDeleteReaction(): (payload: DeleteReactionPayload) => void {
  const { video } = useVideoContext();
  const { password } = useVideoPasswordContext();
  const { pushError } = useErrorStore();
  const deleteAutoReaction = useDeleteAutoReaction();

  const [deleteReactionInternal] = useDeleteVideoReactionMutation({
    onError: err => {
      pushError(DELETE_REACTION_ERROR);
      logger.error(
        err,
        {
          message: REACTION_FETCH_ERROR,
          error: err,
        },
        { feature: Feature.VideoReactions }
      );
    },
  });

  const deleteReaction = (payload: DeleteReactionPayload) => {
    const idToDelete = payload.reactionId;

    if ([AUTO_REACTION_HANDS_ID, AUTO_REACTION_PARTY_ID].includes(idToDelete)) {
      deleteAutoReaction({ reactionId: idToDelete, videoId: video.id });

      return;
    }

    deleteReactionInternal({
      variables: {
        reactionId: idToDelete,
        password,
      },
      optimisticResponse: {
        __typename: 'Mutation',
        deleteVideoReaction: true,
      },
      update: (cache, { data }) => {
        if (data?.deleteVideoReaction) {
          const normalizedId = cache.identify({
            id: idToDelete,
            __typename: 'PublicVideoReaction',
          });

          // Order Apollo to delete that value
          cache.evict({ id: normalizedId });

          // Order Apollo to do a garbage collection
          // Apollo will remove all the references to objects that have
          // been deleted
          cache.gc();
        }
      },
      onCompleted: () => {
        track(EMOJI_REACTION_DELETED, {
          reactor_id: payload.reactionId,
          currentUserIsOwner: video.isOwner,
          video_id: video.modelId,
          sentiment: payload.type,
        });
      },
    });
  };

  return deleteReaction;
}
