import { useGetVideoAutoGenInfoQuery } from '@js/pages/share/edit-tab/GetAutoGetInfo.generated';

export function useAutoGenInfo({
  videoId,
  password,
}: {
  videoId: string;
  password: string | null;
}): { isAutoGenerated: boolean; draftId: string | null } {
  const { data: autoGetInfo } = useGetVideoAutoGenInfoQuery({
    variables: {
      videoId,
      password,
    },
  });

  const response = autoGetInfo?.getVideoAutoGenInfo;

  let isAutoGenerated = false;
  let draftId: string | null = null;

  if (response?.__typename === 'GetVideoAutoGenInfoPayload') {
    isAutoGenerated = response.isAutoGenerated;
    draftId = response.draftId;
  }

  return {
    isAutoGenerated,
    draftId,
  };
}
