import { useThumbnailFlow } from '@js/common/thumbnail-flow';
import { ErrorSeverities } from '@js/constants/error-severities';
import { CUSTOM_THUMBNAIL_ADDED } from '@js/constants/events';

import { useConfirmationToast } from '@js/common/confirmation-toast/useConfirmationToast';
import { useErrorBar } from '@js/common/error-management/error-bar/useErrorBar';
import { useVideoContext } from '@js/common/video-player';
import { parseVideo } from '@js/components/video-player-fresh/utils';
import AvatarEditor from 'react-avatar-editor';
import fetch from '@js/utilities/fetch';
// TODO: Replace with autogenerated hook

import { getGraphQLClient } from '@js/utilities/graphql';
import * as logger from '@js/utilities/loggerx';

import * as analytics from '@js/utilities/analytics';

import { mapThumbnailsFromContextToServer } from '../common/mapThumbnails';
import { UploadVideoThumbnailOptions } from './types';

import { AnalyticsEntityId } from '@loomhq/shared-utilities/utilities/analytics/analyticUtils';
import { withIdentifiers } from '@js/utilities/analytics/attribute-transformer';

export const useUploadVideoThumbnail = ({
  initiateSave,
  currentlyUploading,
  cropperRef,
  thumbnailLocalUrl,
  options,
}: {
  initiateSave: boolean;
  currentlyUploading: boolean;
  cropperRef: React.MutableRefObject<AvatarEditor>;
  thumbnailLocalUrl: string;
  options: UploadVideoThumbnailOptions;
}): void => {
  const { showErrorBar } = useErrorBar();
  const { finishThumbnailSave, toggleThumbnailUploading } = useThumbnailFlow();
  const { setShowConfirmationToast } = useConfirmationToast();

  const {
    video: { id: videoId },
    setVideo,
  } = useVideoContext();

  const gqlClient = getGraphQLClient();

  if (!initiateSave || currentlyUploading || !cropperRef.current) {
    return;
  }

  const { x, y, width, height } = cropperRef.current.getCroppingRect();

  toggleThumbnailUploading();

  const MAX_FILE_SIZE = 1000000 * 4;

  const file = dataUrltoBlob(thumbnailLocalUrl);

  if (file.size > MAX_FILE_SIZE) {
    showErrorBar({
      message: 'Selected file too big. Max 4 MB. Please try again.',
      severity: ErrorSeverities.ERROR,
    });
    toggleThumbnailUploading();

    return;
  }

  const formData = new FormData();

  formData.append('thumbnail', file);
  formData.append('dims', JSON.stringify({ ...options, x, y, width, height }));

  fetch(`/v1/videos/${videoId}`, {
    method: 'PATCH',
    credentials: 'include',
    body: formData,
  })
    .then(response => {
      if (response.status >= 400) {
        throw new Error(`got a bad response status: ${response.status}`);
      }

      toggleThumbnailUploading();
      setShowConfirmationToast('New thumbnail saved');
      finishThumbnailSave();

      analytics.track(
        CUSTOM_THUMBNAIL_ADDED,
        withIdentifiers(
          CUSTOM_THUMBNAIL_ADDED,
          AnalyticsEntityId.video(videoId, 'video_id')
        )
      );

      return response.json();
    })
    .then(video => {
      setVideo(parseVideo(video));
      gqlClient.cache.modify({
        id: gqlClient.cache.identify({
          id: videoId,
          __typename: 'RegularUserVideo',
        }),
        fields: {
          thumbnails: cachedThumbs => {
            const updatedServerThumbnails = mapThumbnailsFromContextToServer(
              video.thumbnails
            );
            const newThumbnails = {
              ...cachedThumbs,
              ...updatedServerThumbnails,
            };

            return newThumbnails;
          },
          defaultThumbnails: cachedDefaultThumbs => {
            const newThumbnails = {
              ...cachedDefaultThumbs,
              default: video.defaultThumbnails.default,
              static: video.defaultThumbnails.static,
            };

            return newThumbnails;
          },
        },
      });
    })
    .catch(error => {
      showErrorBar({
        message: 'Oops! Failed to update video thumbnail.',
        severity: ErrorSeverities.ERROR,
      });

      logger.warning(error, {
        message: 'Error in PATCH to /v1/videos/thumbnail',
      });

      toggleThumbnailUploading();
      finishThumbnailSave();
    });
};

const dataUrltoBlob = dataurl => {
  const arr = dataurl.split(',');
  const mime = arr[0].match(/:(.*?);/)[1];
  const bstr = atob(arr[1]);

  let n = bstr.length;
  const u8arr = new Uint8Array(n);

  while (n--) {
    u8arr[n] = bstr.charCodeAt(n);
  }

  return new Blob([u8arr], { type: mime });
};
