import { AutoresizeMentionTextarea } from '@js/common/autoresize-mention-textarea';
import { SemanticParser } from '@js/common/comments';
import { usePostComment } from '@js/common/comments/comment-creation/usePostComment';
import {
  selectDisplayName,
  useCurrentUserSelector,
} from '@js/common/current-user';
import { ErrorText } from '@js/common/error-management';
import UserAvatar from '@js/components/user-avatar';

import { useGetSelectedWorkspace } from '@js/hooks/workspace-basic';
import React, { MutableRefObject, useMemo, useRef, useState } from 'react';

import {
  getAvatarThumbForUser,
  getUserAvatarThumb,
} from '@js/utilities/avatar';

// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import { searchWorkspaceMembersFn } from '@js/utilities/workspace';

import {
  Align,
  Arrange,
  Button,
  Container,
  Icon,
  Link,
  Spacer,
  Text,
  TextButton,
} from '@loomhq/lens';
import { SvgReplyLeft } from '@loomhq/lens/icons/reply-left';
import useCommentVideoEmbed from '@js/hooks/useCommentVideoEmbed';

import { ProfileCard } from '../ProfileCard';
import styles from './styles.module.less';

const ERROR_MESSAGE = 'Uh oh! Seems like the reply failed to send.';

// Messages with characters more than this value
// will be trimmed to this length by default
export const COMMENT_TRIM_LENGTH = 250;

type CommentContainerProps = {
  name: string;
  avatarSrc: string;
  createdAt: string;
  content?: string;
  profileId?: number;
  timestamp?: string;
  isDimmed?: boolean;
  alertIcon?: React.ReactNode;
  verticallyCenter?: boolean;
  url?: string;
};

export const CommentContainer = ({
  name,
  avatarSrc,
  createdAt,
  profileId,
  content,
  alertIcon,
  timestamp,
  isDimmed,
  verticallyCenter,
  url,
}: CommentContainerProps): JSX.Element => {
  const color = isDimmed && 'bodyDimmed';
  const contentLength = content?.length || 0;
  const [seeMore, setSeeMore] = useState(contentLength > COMMENT_TRIM_LENGTH);

  const ref = useRef();

  useCommentVideoEmbed(ref);

  return (
    <Spacer bottom="medium">
      <Arrange gap={1.5} alignItems={verticallyCenter ? 'center' : 'start'}>
        <ProfileCard
          avatarMode={true}
          notificationOwner={{ avatar: avatarSrc, name, id: profileId }}
        >
          <div className="relative">
            <UserAvatar avatarSize={4} avatarSrc={avatarSrc} name={name} />
            {alertIcon && (
              <Container
                backgroundColor="primary"
                position="absolute"
                bottom="-0.6"
                right="-0.6"
                padding="0.2rem"
                className={styles.iconContainer}
              >
                <Align alignment="center">
                  <Icon icon={<SvgReplyLeft />} size={1.8} color="white" />
                </Align>
              </Container>
            )}
          </div>
        </ProfileCard>
        <div>
          <Arrange alignItems={verticallyCenter ? 'center' : 'start'}>
            <ProfileCard
              avatarMode={false}
              notificationOwner={{ avatar: avatarSrc, name, id: profileId }}
            >
              <Text fontWeight="bold" isInline>
                {name}
              </Text>
            </ProfileCard>
            {timestamp && (
              <div>
                &nbsp;
                <Link className={styles.link} href={url} variant="neutral">
                  <Text color="bodyDimmed" isInline>
                    at {timestamp}
                  </Text>
                </Link>
              </div>
            )}

            <Text color="bodyDimmed" isInline>
              ・{createdAt}
            </Text>
          </Arrange>
          <Text {...(color && { color })}>
            <SemanticParser
              withPills={true}
              comment={{ content }}
              trimLength={seeMore ? COMMENT_TRIM_LENGTH : undefined}
              afterBlock={
                seeMore ? (
                  <TextButton
                    onClick={() => setSeeMore(false)}
                    size="small"
                    offsetSide="left"
                  >
                    See more
                  </TextButton>
                ) : undefined
              }
            />
          </Text>
        </div>
      </Arrange>
    </Spacer>
  );
};

type ReplyInputProps = {
  videoId: string;
  parentPostId: string;
  timestamp: number;
  placeholder: string;
  notificationTrayItemId;
};

export const ReplyInput = ({
  videoId,
  parentPostId,
  timestamp,
  placeholder,
  notificationTrayItemId,
}: ReplyInputProps): JSX.Element => {
  const [input, setInput] = useState('');
  const [errorMessage, setErrorMessage] = useState('');
  const { postComment } = usePostComment(videoId);
  const gqlClient = getGraphQLClient();

  const inputRef: MutableRefObject<HTMLTextAreaElement | null> = useRef(null);

  const displayName = useCurrentUserSelector(selectDisplayName, 'Anonymous');
  const avatars = useCurrentUserSelector(user => user.avatars, []);
  const userId = useCurrentUserSelector(user => user.id, NaN);

  const selectedWorkspace = useGetSelectedWorkspace();
  const fetchFn = searchWorkspaceMembersFn(selectedWorkspace.id);

  const userAvatarSrc = useMemo(() => {
    return getUserAvatarThumb(avatars);
  }, [avatars]);

  const onPostReply = async () => {
    const onCompleted = data => {
      const {
        id,
        user_name: userName,
        createdAt,
        avatar,
        content,
      } = data?.createVideoComment;

      gqlClient.cache.modify({
        id: gqlClient.cache.identify({
          id: notificationTrayItemId,
          __typename: 'NotificationTrayItem',
        }),
        fields: {
          data(cachedData) {
            const replies = cachedData.replies;
            const newReplies = [
              ...replies,
              ...[
                {
                  id,
                  userName,
                  userId,
                  createdAt,
                  avatar:
                    avatar?.thumb && getAvatarThumbForUser([avatar?.thumb]),
                  content,
                  timestamp,
                },
              ],
            ];

            const newData = { ...cachedData };

            newData.replies = newReplies;

            return newData;
          },
        },
      });
    };

    try {
      await postComment({
        anonUserName: '',
        comment: input,
        parentPostId,
        timestamp,
        videoId,
        onCompleted,
      });

      setErrorMessage('');
      setInput('');
    } catch (err) {
      setErrorMessage(ERROR_MESSAGE);
    }
  };

  return (
    <>
      <Arrange
        gap={1.5}
        columns={input ? ['2rem', '1fr', 'auto'] : ['2rem', '1fr']}
        alignItems="start"
      >
        <UserAvatar
          avatarSize={4}
          avatarSrc={userAvatarSrc}
          name={displayName}
        />

        <AutoresizeMentionTextarea
          dataTestId="notification-reply-field"
          fetch={fetchFn}
          hasError={Boolean(errorMessage)}
          onChange={e => {
            setErrorMessage('');
            setInput(e.target.value);
          }}
          onKeyDown={e => {
            if (e.code === 'Enter' && !e.shiftKey) {
              onPostReply();
              e.preventDefault();
            }
          }}
          placeholder={placeholder}
          shouldHighlight
          textRef={inputRef}
          value={input}
          ariaLabel="Reply to video or add others with @"
        />

        {input && (
          <Button
            variant="primary"
            onClick={e => {
              e.stopPropagation();
              e.preventDefault();
              onPostReply();
            }}
          >
            Send
          </Button>
        )}
      </Arrange>

      <ErrorText marginLeft={5.5} error={errorMessage} />
    </>
  );
};

export const NotificationLink = ({
  url,
  children,
}: {
  url: string;
  children: JSX.Element | string;
}): JSX.Element => (
  <span className={styles.linkContainer}>
    <Link href={url} variant="neutral" className={styles.link}>
      <Text fontWeight="bold" isInline>
        {children}
      </Text>
    </Link>
  </span>
);
