// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';

import UpdateUserProperty from '@js/hooks/user/UpdateUserProperty.graphql';

// this helps while trying to troubleshoot FTUX issues
export const enableFtuxReset = (): void => {
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  window.loomResetFtux = async (ftuxKey: string): Promise<string> => {
    const gqlClient = getGraphQLClient();

    try {
      await gqlClient.mutate({
        mutation: UpdateUserProperty,
        variables: {
          name: ftuxKey,
          value: false,
        },
      });

      return `FTUX "${ftuxKey}" reset! You should refresh the page now.`;
    } catch (err) {
      return `Error resetting FTUX "${ftuxKey}": ${err}`;
    }
  };
};
