// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';

import formatDistanceToNow from 'date-fns/formatDistanceToNow';
import pluralize from 'pluralize';
import React from 'react';

import { Arrange, Button, Container, Spacer, Text } from '@loomhq/lens';
import { spacesUtils } from '@loomhq/shared-utilities';
import { SpacesAvatar } from '@js/common/spaces';

import GetSpace from '@js/components/spaces/graphql/GetSpace.gql';
import UserAvatar from '@js/components/user-avatar';
import { SPACES_PAGE } from '@js/constants/routes';

import { ProfileCard } from '../../ProfileCard';
import { VisitSpaceCardProps } from '../../types';
import { getNotificationOwner } from '../utils';

const { getSlug } = spacesUtils;

export const VisitSpaceCard = ({
  notification,
  title,
  action,
  onClick,
}: {
  notification: VisitSpaceCardProps;
  title: string;
  action: string | JSX.Element;
  onClick?: () => void;
}): JSX.Element => {
  const spaceId = notification.data.spaceId;
  // TODO: Replace with autogenerated hook
  const { data: spaceData } = useQuery(GetSpace, {
    fetchPolicy: 'no-cache',
    variables: { spaceId },
  });

  const spaceMemberCount = spaceData?.getSpace?.space?.membersCount;
  const spaceVideoCount = spaceData?.getSpace?.space?.totalVideos;

  let spaceInfo = '';

  if (spaceMemberCount >= 0) {
    spaceInfo = `・${spaceMemberCount} ${pluralize(
      'member',
      spaceMemberCount
    )} `;
  }

  if (spaceVideoCount >= 0) {
    spaceInfo += `・${spaceVideoCount} ${pluralize('video', spaceVideoCount)} `;
  }

  const notificationOwner = getNotificationOwner(notification.user);

  return (
    <Arrange
      gap="xlarge"
      columns={{
        default: '1fr',
        small: ['minmax(0, 43.25rem)', 'minmax(250px, auto)'],
      }}
      alignItems="start"
      justifyContent="space-between"
    >
      <Container>
        <Container paddingBottom="medium">
          <Text color="bodyDimmed" isInline htmlTag="h2">
            {title}
          </Text>
          {notification.user && (
            <>
              <Spacer bottom={2} />
              <Arrange gap={1.5} alignItems="center">
                <ProfileCard
                  avatarMode={true}
                  notificationOwner={notificationOwner}
                >
                  <UserAvatar
                    avatarSize={4}
                    avatarSrc={notificationOwner.avatar ?? ''}
                    name={notificationOwner.name}
                  />
                </ProfileCard>
                <Arrange gap="xsmall">
                  <ProfileCard
                    avatarMode={false}
                    notificationOwner={notificationOwner}
                  >
                    <Text fontWeight="bold" isInline>
                      {notificationOwner.name}
                    </Text>
                  </ProfileCard>
                  <Text color="bodyDimmed" isInline>
                    {action}
                    {`・${formatDistanceToNow(
                      new Date(notification.createdAt),
                      { addSuffix: true }
                    )}`}
                  </Text>
                </Arrange>
              </Arrange>
            </>
          )}
        </Container>
        <Container
          borderSide="all"
          radius="medium"
          padding="medium"
          overflow="hidden"
        >
          <Container>
            <Arrange gap="medium">
              <SpacesAvatar
                spaceName={notification.data.spaceName}
                size={'large'}
              />

              <Container>
                <Text fontWeight="bold" isInline>
                  {notification.data.spaceName}
                </Text>
                <Arrange>
                  <Text color="bodyDimmed" isInline>
                    Space
                  </Text>
                  {spaceInfo.length > 0 && (
                    <Text color="bodyDimmed" isInline>
                      {spaceInfo}
                    </Text>
                  )}
                </Arrange>
              </Container>
            </Arrange>
          </Container>
          <Arrange gap="small" justifyContent="end">
            <Button
              variant="primary"
              onClick={() => {
                onClick && onClick();
                window.location.href = `${SPACES_PAGE}/${getSlug({
                  id: notification.data.spaceId,
                  name: notification.data.spaceName,
                })}`;
              }}
            >
              Visit Space
            </Button>
          </Arrange>
        </Container>
      </Container>
    </Arrange>
  );
};
