import { ApolloClient } from '@apollo/client';
import { FetchResult } from '@apollo/client/link/core';

// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';
import CorrectWords from '@js/utilities/transcript/CorrectWords.graphql';

import CreateCorrections from '@js/utilities/transcript/CreateCorrections.graphql';
import RemoveAllCorrections from '@js/utilities/transcript/RemoveAllCorrections.graphql';
import RevertAllCorrections from '@js/utilities/transcript/RevertAllCorrections.graphql';
import { CreateTranscriptCorrectionsNewCorrectionV2Input } from '@js/globalTypes.generated';

import type {
  CorrectionResult,
  RevertAllResult,
  WordCorrection,
  TranscriptMutationResult,
} from '@loomhq/shared-utilities';

export type CorrectionCreationResult = {
  message?: string;
  version: string;
  captionsUrl: string;
  phrasesUrl: string;
};

const ERROR_MESSAGE = 'Corrections could not be saved!';

export const correctWords = (
  correction: WordCorrection,
  password: string
): Promise<TranscriptMutationResult | null> => {
  const gqlClient: ApolloClient<Record<string, unknown>> = getGraphQLClient();

  return gqlClient
    .mutate({
      mutation: CorrectWords,
      variables: { ...correction, password },
    })
    .then((result: FetchResult<CorrectionResult>) => {
      return result.data?.updateVideoTranscript ?? null;
    })
    .catch(
      () =>
        ({
          message: ERROR_MESSAGE,
        }) as TranscriptMutationResult
    );
};

export const revertAll = (
  videoId: string,
  password: string
): Promise<TranscriptMutationResult | null> => {
  const gqlClient: ApolloClient<Record<string, unknown>> = getGraphQLClient();

  return gqlClient
    .mutate({
      mutation: RevertAllCorrections,
      variables: { videoId, password },
    })
    .then((result: FetchResult<RevertAllResult>) => {
      return result.data ? result.data.revertAllTranscriptCorrections : null;
    })
    .catch(
      () =>
        ({
          message: ERROR_MESSAGE,
        }) as TranscriptMutationResult
    );
};

// New Transcript Architecture
const executeMutation = async <M extends { message?: string }>(
  mutation: any,
  variables: Record<string, unknown>,
  successTypeName: string,
  dataKey: string
): Promise<M | null> => {
  const gqlClient: ApolloClient<Record<string, unknown>> = getGraphQLClient();

  try {
    const result = await gqlClient.mutate({
      mutation,
      variables,
    });

    const response = result.data?.[dataKey];

    if (response?.__typename === successTypeName) {
      return { ...response } as M;
    }

    // let's handle unexpected errors in the catch block
    throw new Error('Invalid response type');
  } catch {
    // catching unexpected errors such as 500 or any other unrelated API errors
    return {
      message: ERROR_MESSAGE,
    } as M;
  }
};

export const removeAllCorrections = (
  videoId: string
): Promise<TranscriptMutationResult | null> =>
  executeMutation<TranscriptMutationResult>(
    RemoveAllCorrections,
    { videoId },
    'RemoveAllTranscriptCorrectionsPayload',
    'removeAllTranscriptCorrections'
  );

export const createCorrections = (
  videoId: string,
  corrections: CreateTranscriptCorrectionsNewCorrectionV2Input[]
): Promise<CorrectionCreationResult | null> =>
  executeMutation<CorrectionCreationResult>(
    CreateCorrections,
    { videoId, transcriptCorrections: corrections },
    'CreateTranscriptCorrectionsV2Payload',
    'createTranscriptCorrectionsV2'
  );
