import { useCallback } from 'react';

import { RequestPlanUpgradeLocations } from '@js/constants/requestPlanUpgradeLocations';
import { ATLASSIAN_PRICING_QUOTES, CONTACT_SALES } from '@js/constants/routes';

import { ApolloClient, NormalizedCacheObject } from '@apollo/client';
import { getAtlassianAnalyticsClient } from '@js/common/analytics';
import { addOriginTracing } from '@js/common/atlassian-analytics/origin-tracing';
import { selectFromCurrentUserCache } from '@js/common/current-user/cache/selectFromCurrentUserCache';
import { useModals } from '@js/common/modal-container/useModals';
import {
  GetAggPlanUrlAndProductDocument,
  GetAggPlanUrlAndProductQuery,
} from '@js/utilities/billing/GetAGGPlanUrlAndProduct.generated';
import { navigateToCheckout } from '@js/utilities/billing/checkout';
// TODO: Replace with autogenerated hook
// eslint-disable-next-line no-restricted-imports
import { getGraphQLClient } from '@js/utilities/graphql';
import { isAtlassianManagedWorkspace } from '@js/utilities/workspace';

import {
  ATLASSIAN_LOOM_BUSINESS_AI_LEVEL,
  ATLASSIAN_LOOM_BUSINESS_AI_OFFERING_KEY,
} from '@loomhq/billing-core/constant';
import { getProductGrants } from '@loomhq/billing-core/utility';
import {
  ORG_ROLE_ADMIN,
  ORG_ROLE_CREATOR,
  ORG_ROLE_CREATOR_LITE,
  ORG_ROLE_VIEWER,
} from '@loomhq/shared-utilities/constants/organizationRoles';
import { SALES_SUPPORT_TYPE_LED } from '@loomhq/shared-utilities/constants/salesSupportTypes';
import {
  WORKSPACE_PLAN_BUSINESS,
  WORKSPACE_PLAN_ENTERPRISE,
  WORKSPACE_PLAN_STARTER_FREE,
} from '@loomhq/shared-utilities/constants/workspacePlans';
import { UPGRADE_TYPES } from '@loomhq/shared-utilities/constants/workspaceUpgradeRequests';
import { Addon } from '@js/globalTypes.generated';
import * as analytics from '@js/utilities/analytics';

import { useGetPaywallRequestDataLazyQuery } from './get-paywall-request-data.generated';

import { AnalyticsEntityId } from '@loomhq/shared-utilities/utilities/analytics/analyticUtils';
import { withIdentifiers } from '../../utilities/analytics/attribute-transformer';
import { useGetWorkspaceMemberships } from '@js/common/workspace-memberships/use-get-workspace-memberships';

type Paywall = 'business' | 'loom-ai' | 'enterprise';

interface PaywallRequestOptions {
  analyticEvent: string;
  source?: RequestPlanUpgradeLocations;
}

type PaywallRequest = (
  paywall: Paywall,
  options?: PaywallRequestOptions
) => Promise<void>;

export const usePaywallRequest = (): PaywallRequest => {
  const { selectedWorkspace: workspace } = useGetWorkspaceMemberships();
  const memberRole = workspace?.memberRole;
  const atlassianManagedWorkspace = isAtlassianManagedWorkspace(
    workspace ?? null
  );
  const graphqlClient = getGraphQLClient();

  const [getPaywallRequestData] = useGetPaywallRequestDataLazyQuery();

  const handlePaywallRequest = useCallback(
    async (paywall: Paywall, options?: PaywallRequestOptions) => {
      if (!workspace) {
        return;
      }

      if (atlassianManagedWorkspace) {
        return handleAtlassianPaywall(workspace.id, paywall, graphqlClient);
      }
      const queryResult = await getPaywallRequestData({
        variables: {
          workspaceId: workspace?.id,
        },
      });

      const billing = queryResult.data?.billing?.billing_details;
      const requestStatus =
        queryResult.data?.request_status?.__typename ===
        'GetUpgradeWorkspaceRequestStatusPayload'
          ? queryResult.data.request_status.status
          : null;

      const addOns = billing?.add_ons ?? [];

      const aiAddOn = addOns.find(
        a => getProductGrants(a.price.product).addon === Addon.Ai
      );

      const isSalesLedAccount =
        (workspace.organization_properties as any)?.salesSupportType ===
        SALES_SUPPORT_TYPE_LED;

      const pureTrial = Boolean(billing?.plan?.pure_trial);
      const paused = Boolean(billing?.paused);

      if (paywall === 'business') {
        const fn = () =>
          handleBusinessPaywall({
            workspace,
            memberRole,
            requestStatus,
            pureTrial,
            paused,
          });

        if (options) {
          analytics.track(
            options.analyticEvent,
            {
              ...withIdentifiers(
                options.analyticEvent,
                AnalyticsEntityId.user(
                  selectFromCurrentUserCache(user => user.id, undefined),
                  'userId'
                ),
                AnalyticsEntityId.workspace(
                  workspace.id,
                  'string',
                  'workspaceId'
                )
              ),
              workspacePlan: workspace.type,
              source: options.source,
              isAiCta: false,
            },
            fn
          );
        } else {
          fn();
        }
      } else if (paywall === 'loom-ai') {
        const fn = () =>
          handleLoomAiPaywall({
            workspace,
            memberRole,
            pureTrial,
            requestStatus,
            aiAddOn,
            isSalesLedAccount,
            paused,
          });

        if (options) {
          analytics.track(
            options.analyticEvent,
            {
              ...withIdentifiers(
                options.analyticEvent,
                AnalyticsEntityId.user(
                  selectFromCurrentUserCache(user => user.id, undefined),
                  'userId'
                ),
                AnalyticsEntityId.workspace(
                  workspace.id,
                  'string',
                  'workspaceId'
                )
              ),
              workspacePlan: workspace.type,
              source: options.source,
              isAiCta: true,
            },
            fn
          );
        } else {
          fn();
        }
      } else if (paywall === 'enterprise') {
        const fn = () =>
          handleEnterprisePaywall({
            workspace,
            memberRole,
            requestStatus,
          });

        if (options) {
          analytics.track(
            options.analyticEvent,
            {
              ...withIdentifiers(
                options.analyticEvent,
                AnalyticsEntityId.user(
                  selectFromCurrentUserCache(user => user.id, undefined),
                  'userId'
                ),
                AnalyticsEntityId.workspace(
                  workspace.id,
                  'string',
                  'workspaceId'
                )
              ),
              workspacePlan: workspace.type,
              source: options.source,
              isAiCta: false,
            },
            fn
          );
        } else {
          fn();
        }
      }
    },
    [
      workspace,
      memberRole,
      atlassianManagedWorkspace,
      graphqlClient,
      getPaywallRequestData,
    ]
  );

  return handlePaywallRequest;
};

async function handleAtlassianPaywall(
  workspaceId: string,
  paywall: Paywall,
  graphqlClient: ApolloClient<NormalizedCacheObject>
) {
  const { openModal } = useModals.getState();
  const analyticsClient = getAtlassianAnalyticsClient();
  const result = await graphqlClient.query<GetAggPlanUrlAndProductQuery>({
    query: GetAggPlanUrlAndProductDocument,
    variables: {
      workspaceId,
      offeringKey: ATLASSIAN_LOOM_BUSINESS_AI_OFFERING_KEY,
    },
  });

  const upgradeUrl =
    result.data?.planUrl?.__typename === 'GetAGGChangePlanUrlPayload'
      ? result.data.planUrl.url
      : ATLASSIAN_PRICING_QUOTES;
  const { url: updatedUrl, origin } = addOriginTracing(upgradeUrl);

  const isAvailableToUser =
    result.data?.planUrl?.__typename === 'GetAGGChangePlanUrlPayload'
      ? result.data.planUrl.isAvailableToUser
      : null;

  const currentLoomProductLevel =
    result?.data?.entitlements?.__typename ===
    'GetWorkspaceAGGEntitlementsPayload'
      ? result.data.entitlements.entitlements[0]?.currentLoomProductLevel
      : null;
  const isAvailableUpgrade =
    currentLoomProductLevel &&
    currentLoomProductLevel < ATLASSIAN_LOOM_BUSINESS_AI_LEVEL;

  if (isAvailableToUser) {
    const event = {
      source: 'loom',
      action: 'upgrade_button_clicked',
      actionSubject: 'atlassian_plan_and_billing_upgrade_button',
      attributes: {
        application: 'loom',
        ...origin.toAnalyticsAttributes({ hasGeneratedId: true }),
        user_id: selectFromCurrentUserCache(user => user.id, undefined),
        workspace_id: workspaceId,
      },
    };
    await analyticsClient.sendTrackEvent(event);
    window.location.href = updatedUrl;
  } else if (isAvailableUpgrade && paywall === 'business') {
    openModal({
      modalType: 'REQUEST_UPGRADE_MODAL',
      options: {
        upgradeType: UPGRADE_TYPES.PLAN,
      },
    });
  } else if (isAvailableUpgrade && paywall === 'loom-ai') {
    openModal({
      modalType: 'REQUEST_UPGRADE_MODAL',
      options: {
        upgradeType: UPGRADE_TYPES.ADD_ON,
      },
    });
  }
}

function handleBusinessPaywall({
  workspace,
  memberRole,
  requestStatus,
  pureTrial,
  paused,
}) {
  const { openModal } = useModals.getState();
  switch (workspace?.type) {
    case WORKSPACE_PLAN_BUSINESS: {
      if (pureTrial) {
        switch (memberRole) {
          case ORG_ROLE_ADMIN: {
            navigateToCheckout();
            break;
          }
          case ORG_ROLE_CREATOR:
          case ORG_ROLE_CREATOR_LITE:
            openModal({
              modalType: 'REQUEST_UPGRADE_MODAL',
              options: {
                upgradeType: UPGRADE_TYPES.PLAN,
                requestStatus,
              },
            });
            break;
          default:
            return;
        }
      } else {
        switch (memberRole) {
          case ORG_ROLE_CREATOR:
            openModal({
              modalType: 'REQUEST_UPGRADE_MODAL',
              options: {
                upgradeType: UPGRADE_TYPES.ADD_ON,
                requestStatus,
              },
            });
            break;
          case ORG_ROLE_CREATOR_LITE:
            openModal({
              modalType: 'REQUEST_UPGRADE_MODAL',
              options: {
                upgradeType: UPGRADE_TYPES.ROLE,
                requestStatus,
              },
            });
            break;
          default:
            return;
        }
      }

      break;
    }
    case WORKSPACE_PLAN_STARTER_FREE: {
      switch (memberRole) {
        case ORG_ROLE_ADMIN:
          if (paused) {
            return openModal({ modalType: 'RESUME_PAUSED_SUBSCRIPTION_MODAL' });
          }

          return navigateToCheckout();
        case ORG_ROLE_CREATOR:
        case ORG_ROLE_CREATOR_LITE:
          openModal({
            modalType: 'REQUEST_UPGRADE_MODAL',
            options: {
              upgradeType: UPGRADE_TYPES.PLAN,
              requestStatus,
            },
          });
          return;

        default:
          return;
      }
    }
    case WORKSPACE_PLAN_ENTERPRISE: {
      switch (memberRole) {
        case ORG_ROLE_VIEWER: {
          openModal({
            modalType: 'REQUEST_UPGRADE_MODAL',
            options: {
              upgradeType: UPGRADE_TYPES.ROLE,
              requestStatus,
            },
          });
          return;
        }
        default:
          return;
      }
    }
    default:
      return;
  }
}

function handleEnterprisePaywall({ workspace, memberRole, requestStatus }) {
  const { openModal } = useModals.getState();
  const contactSalesUrl = new URL(CONTACT_SALES, window.location.origin);
  switch (workspace?.type) {
    case WORKSPACE_PLAN_BUSINESS: {
      switch (memberRole) {
        case ORG_ROLE_ADMIN: {
          window.open(contactSalesUrl.toString(), '_blank');
          break;
        }
        case ORG_ROLE_CREATOR:
        case ORG_ROLE_CREATOR_LITE:
          openModal({
            modalType: 'REQUEST_UPGRADE_MODAL',
            options: {
              upgradeType: UPGRADE_TYPES.PLAN,
              requestStatus,
            },
          });
          break;
        default:
          return;
      }

      break;
    }
    case WORKSPACE_PLAN_STARTER_FREE: {
      switch (memberRole) {
        case ORG_ROLE_ADMIN:
          window.open(contactSalesUrl.toString(), '_blank');
          break;
        case ORG_ROLE_CREATOR:
        case ORG_ROLE_CREATOR_LITE:
          openModal({
            modalType: 'REQUEST_UPGRADE_MODAL',
            options: {
              upgradeType: UPGRADE_TYPES.PLAN,
              requestStatus,
            },
          });
          return;
        default:
          return;
      }

      break;
    }
    case WORKSPACE_PLAN_ENTERPRISE: {
      switch (memberRole) {
        case ORG_ROLE_VIEWER: {
          openModal({
            modalType: 'REQUEST_UPGRADE_MODAL',
            options: {
              upgradeType: UPGRADE_TYPES.ROLE,
              requestStatus,
            },
          });
          return;
        }
        case ORG_ROLE_CREATOR: {
          openModal({
            modalType: 'REQUEST_UPGRADE_MODAL',
            options: {
              upgradeType: UPGRADE_TYPES.ROLE,
              requestStatus,
              minRoleForFeature: 'admin',
            },
          });
          return;
        }
        default:
          return;
      }
    }
    default:
      return;
  }
}

function handleLoomAiPaywall({
  workspace,
  pureTrial,
  memberRole,
  requestStatus,
  aiAddOn,
  isSalesLedAccount,
  paused,
}) {
  const { openModal } = useModals.getState();
  switch (workspace?.type) {
    case WORKSPACE_PLAN_BUSINESS: {
      if (pureTrial) {
        switch (memberRole) {
          case ORG_ROLE_ADMIN:
            if (isSalesLedAccount) {
              window.location.href = 'https://www.loom.com/connect/enterprise';
            } else {
              navigateToCheckout();
            }

            break;
          case ORG_ROLE_CREATOR:
          case ORG_ROLE_CREATOR_LITE:
          case ORG_ROLE_VIEWER:
            openModal({
              modalType: 'REQUEST_UPGRADE_MODAL',
              options: {
                upgradeType: UPGRADE_TYPES.ADD_ON,
                requestStatus,
              },
            });
            break;
          default:
            return;
        }
      } else {
        if (aiAddOn) {
          switch (memberRole) {
            case ORG_ROLE_CREATOR_LITE:
            case ORG_ROLE_VIEWER:
              openModal({
                modalType: 'REQUEST_UPGRADE_MODAL',
                options: {
                  upgradeType: UPGRADE_TYPES.ROLE,
                  requestStatus,
                },
              });
              break;
            default:
              return;
          }
        } else {
          switch (memberRole) {
            case ORG_ROLE_ADMIN:
              if (isSalesLedAccount) {
                window.location.href =
                  'https://www.loom.com/connect/enterprise';
              } else {
                openModal({
                  modalType: 'PURCHASE_AI_MODAL',
                  options: {
                    source: 'handleLoomAiPaywall',
                  },
                });
              }

              break;
            case ORG_ROLE_CREATOR:
            case ORG_ROLE_CREATOR_LITE:
            case ORG_ROLE_VIEWER:
              openModal({
                modalType: 'REQUEST_UPGRADE_MODAL',
                options: {
                  upgradeType: UPGRADE_TYPES.ADD_ON,
                  requestStatus,
                },
              });
              break;
            default:
              return;
          }
        }
      }

      break;
    }

    case WORKSPACE_PLAN_ENTERPRISE: {
      if (aiAddOn) {
        switch (memberRole) {
          case ORG_ROLE_VIEWER:
            openModal({
              modalType: 'REQUEST_UPGRADE_MODAL',
              options: {
                upgradeType: UPGRADE_TYPES.ROLE,
                requestStatus,
              },
            });
            break;

          case ORG_ROLE_CREATOR_LITE:
            openModal({
              modalType: 'REQUEST_UPGRADE_MODAL',
              options: {
                upgradeType: UPGRADE_TYPES.ROLE,
                requestStatus,
              },
            });
            break;
          default:
            return;
        }
      } else {
        switch (memberRole) {
          case ORG_ROLE_ADMIN:
            window.location.href = 'https://www.loom.com/connect/enterprise';

            break;
          case ORG_ROLE_CREATOR:
          case ORG_ROLE_CREATOR_LITE:
          case ORG_ROLE_VIEWER:
            openModal({
              modalType: 'REQUEST_UPGRADE_MODAL',
              options: {
                upgradeType: UPGRADE_TYPES.ADD_ON,
                requestStatus,
              },
            });
            break;

          default:
            return;
        }
      }

      break;
    }

    case WORKSPACE_PLAN_STARTER_FREE: {
      switch (memberRole) {
        case ORG_ROLE_ADMIN:
          if (paused) {
            return openModal({ modalType: 'RESUME_PAUSED_SUBSCRIPTION_MODAL' });
          }

          return navigateToCheckout();
        case ORG_ROLE_CREATOR:
        case ORG_ROLE_CREATOR_LITE:
          openModal({
            modalType: 'REQUEST_UPGRADE_MODAL',
            options: {
              upgradeType: UPGRADE_TYPES.ADD_ON,
              requestStatus,
            },
          });
          return;
        default:
          return;
      }
    }
    default:
      return;
  }
}
