/* eslint-disable @loomhq/loom/no-js-extension */
import {
  PERSISTENT_RECORD_NO_RECORDER_FALLBACK_SHOWN,
  RECORD_BUTTON_CLICKED,
} from '@js/constants/events';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';
import { useIsCurrentUserLoggedIn } from '@js/common/current-user';
import {
  CHECKLIST_RECORD_BUTTON_MODAL,
  SDK_RECORDING_LOADING_MODAL,
} from '@js/common/modal-container';
import { useModals } from '@js/common/modal-container/useModals';
import React from 'react';
import { getFlagValueForUser } from '@js/utilities/featureFlag';
import * as logger from '@js/utilities/loggerx';
import { incrementMetric } from '@js/utilities/metrics';

import { FIX_PERSISTENT_RECORD_MULTIPLE_RECORDERS_TRIGGERING_NUMBER_VARIANT } from '@loomhq/shared-utilities/constants/featureFlag';
import { Feature } from '@loomhq/shared-utilities/constants/product';
import * as analytics from '@js/utilities/analytics';
import { mergeListeners } from '@js/utilities/merge-listeners';

import CreateAnonPartnerSessionRecordingCache from './CreateAnonPartnerSessionRecordingCache.graphql';
import { CHROME_EXTENSION, DESKTOP, SDK } from './constants';
import {
  startChromeExtensionRecording,
  startDesktopRecording,
  startSDKRecording,
} from './utilities';

export const PERSISTENT_RECORD_BUTTON = 'persistent-record';
export const SHARE_PAGE = 'share-page';
export const OTHER = 'other';
export const REMINDER_TO_RECORD_NOTIFICATION =
  'reminder-to-record-notification';
export const ONBOARDING_CHECKLIST = 'onboarding-checklist';

export function RecordButton({
  children,
  priorityList = [CHROME_EXTENSION, DESKTOP, SDK],
  source = PERSISTENT_RECORD_BUTTON,
  location = OTHER,
  shouldLaunchExtensionTutorial = false,
}) {
  const { onButtonClick } = useRecordButtonClick({
    priorityList,
    source,
    location,
    shouldLaunchExtensionTutorial,
  });

  const child = React.Children.only(children);

  return React.cloneElement(child, {
    onClick: mergeListeners(onButtonClick, child.props.onClick),
  });
}

export function useRecordButtonClick({
  priorityList = [CHROME_EXTENSION, DESKTOP, SDK],
  source = PERSISTENT_RECORD_BUTTON,
  location = OTHER,
  shouldLaunchExtensionTutorial = false,
}) {
  const { closeModal, openModal } = useModals();
  const isLoggedIn = useIsCurrentUserLoggedIn();
  // TODO: Replace with autogenerated hook
  const [createAnonPartnerSessionRecordingCache] = useMutation(
    CreateAnonPartnerSessionRecordingCache,
    {
      onCompleted: ({ result }) => {
        if (
          result.__typename !== 'createAnonPartnerSessionRecordingCachePayload'
        ) {
          logger.error(
            new Error(result.message),
            {},
            { feature: Feature.RecorderSDK }
          );
        }
      },
    }
  );

  const initiateRecorder = async count => {
    const waitForDesktopInitFromFlag = await getFlagValueForUser({
      flag: FIX_PERSISTENT_RECORD_MULTIPLE_RECORDERS_TRIGGERING_NUMBER_VARIANT,
    });

    const recorder = priorityList[count];
    let hasStartedRecorder = null;

    switch (recorder) {
      case DESKTOP: {
        hasStartedRecorder = await startDesktopRecording(
          source,
          waitForDesktopInitFromFlag
        );

        break;
      }

      case CHROME_EXTENSION: {
        hasStartedRecorder = await startChromeExtensionRecording(
          source,
          shouldLaunchExtensionTutorial
        );

        break;
      }

      default: {
        hasStartedRecorder = await startSDKRecording({
          source,
          isLoggedIn,
          onRecordingComplete() {
            openModal({ modalType: SDK_RECORDING_LOADING_MODAL });
          },
          onUploadComplete(oembed) {
            closeModal();

            if (source === PERSISTENT_RECORD_BUTTON && !isLoggedIn) {
              createAnonPartnerSessionRecordingCache({
                variables: { videoId: oembed.id },
              });
            }
          },
        });

        if (!hasStartedRecorder) {
          analytics.track(PERSISTENT_RECORD_NO_RECORDER_FALLBACK_SHOWN);
          incrementMetric('recorder_initiate.no_recorder_fallback_modal', {
            source,
          });
          openModal({
            modalType: CHECKLIST_RECORD_BUTTON_MODAL,
            options: {
              source,
            },
          });
        }
      }
    }

    if (!hasStartedRecorder && count < priorityList.length - 1) {
      initiateRecorder(count + 1);
    }
  };

  const onButtonClick = () => {
    analytics.track(RECORD_BUTTON_CLICKED, { source, location });
    incrementMetric('button.click', {
      source,
      isLoggedIn,
    });
    initiateRecorder(0);
  };

  return {
    onButtonClick,
  };
}
