/* eslint-disable @loomhq/loom/no-js-extension */
import { WORKSPACE_SUGGESTION_CLICK } from '@js/constants/events';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';

import { FacePile } from '@js/common/face-pile';
import React from 'react';

import { getAvatarThumbForUser } from '@js/utilities/avatar';

import { Arrange, Button, Container, IconButton, Text } from '@loomhq/lens';
import { SvgClose } from '@loomhq/lens/icons/close';
import { REQUEST_TO_JOIN_WORKSPACE_AUTOJOINED } from '@loomhq/shared-utilities/constants/organizationInvitations';
import { REQUEST_STATUSES } from '@loomhq/shared-utilities/constants/workspaceJoinRequests';
import RequestToJoinWorkspace from '@js/utilities/RequestToJoinWorkspace.graphql';
import * as analytics from '@js/utilities/analytics';

import { useSuggestedWorkspaceWorkspaceSwitcherDismissalState } from '@js/utilities/localStorage/suggestedWorkspace';
import { withIdentifiers } from '@js/utilities/analytics/attribute-transformer';
import { AnalyticsEntityId } from '@loomhq/shared-utilities/utilities/analytics/analyticUtils';

export function SuggestedWorkspace({ suggestedWorkspaceData }) {
  // TODO: Replace with autogenerated hook
  const [requestToJoinWorkspace] = useMutation(RequestToJoinWorkspace);
  const [suggestionDismissed, dismissSuggestion] =
    useSuggestedWorkspaceWorkspaceSwitcherDismissalState();

  async function onRequestClick() {
    const { data } = await requestToJoinWorkspace({
      variables: { workspaceId: workspace.id },
    });

    analytics.track(WORKSPACE_SUGGESTION_CLICK, {
      source: 'workspace-selector',
      status: data.result.status,
      ...withIdentifiers(
        WORKSPACE_SUGGESTION_CLICK,
        AnalyticsEntityId.workspace(
          workspace.id,
          'string',
          'suggestedWorkspaceId'
        )
      ),
    });

    if (data.result.status === REQUEST_TO_JOIN_WORKSPACE_AUTOJOINED) {
      // The user's default workspace has changed, so let's take them to their new workspace
      window.location.href = '/';
    }
  }

  const { workspace, requestStatus, hasPendingInvitation } =
    suggestedWorkspaceData.result;
  const memberCount = workspace.counts?.users?.total_active_workspace_users;

  if (
    requestStatus === REQUEST_STATUSES.APPROVED ||
    hasPendingInvitation ||
    suggestionDismissed
  ) {
    return null;
  }

  return (
    <Container backgroundColor="highlight" padding="medium">
      <Arrange gap="medium" justifyContent="space-between">
        <Arrange autoFlow="row" gap="small">
          <Text fontWeight="bold">
            {suggestedWorkspaceData.result.workspace.name}
          </Text>
          <Arrange gap="small">
            <FacePile
              userData={suggestedWorkspaceData.result.workspace.members.nodes.map(
                ({ user }) => ({
                  name: user.first_name,
                  avatarSrc: getAvatarThumbForUser(user.avatars),
                })
              )}
              maxImages={4}
              alignment="left"
              avatarSize={3}
            />

            {memberCount && memberCount > 4 && (
              <Text size="body-sm" color="bodyDimmed">
                +{memberCount - 4}
              </Text>
            )}
          </Arrange>
        </Arrange>
        <div>
          {requestStatus === REQUEST_STATUSES.PENDING ? (
            <Text color="bodyDimmed" fontWeight="bold">
              Pending
            </Text>
          ) : (
            <Arrange gap="xsmall">
              <Button onClick={onRequestClick} variant="primary" size="small">
                Join
              </Button>
              <IconButton
                altText="Dismiss"
                onClick={() => dismissSuggestion()}
                icon={<SvgClose />}
                size="small"
              />
            </Arrange>
          )}
        </div>
      </Arrange>
    </Container>
  );
}
