// eslint-disable-next-line no-restricted-imports
import { useQuery } from '@apollo/client';

import React from 'react';

import { mentionUtils } from '@loomhq/shared-utilities';

// TODO: File below should become colocated once its other consumers are migrated properly
import GetUserByIdWithProfile from '@js/components/user-profile/profile-card/GetUserByIdWithProfile.graphql';

import { MentionPill } from './mention-pill';

/**
 * @param {Object} props
 * @param {MentionRecord} props.mention
 * @param {Boolean} props.withPills
 * @returns {React.ReactElement}
 *  the mention instance from shared/utilities/mention.js dedicated to Workspace Contacts
 */
const WorkspaceContactMention = ({ mention: { displayText }, withPills }) =>
  !withPills ? (
    <>{`@${displayText}`}</>
  ) : (
    <MentionPill key={displayText} teamMember={undefined} name={displayText} />
  );

const UserMention: any = ({ mention, withPills }) => {
  const { modelId: userId, displayText } = mention;
  const { loading, error, userProfileData } = UserMention.useComponent({
    userId,
  });

  const shouldRenderPlainText = loading || error || !withPills;
  const finalDisplayName = userProfileData
    ? `${userProfileData.first_name} ${userProfileData.last_name}`
    : displayText;

  return shouldRenderPlainText ? (
    <>{`@${finalDisplayName}`}</>
  ) : (
    <MentionPill
      key={finalDisplayName}
      teamMember={userProfileData}
      name={finalDisplayName}
    />
  );
};

UserMention.useComponent = ({ userId }) => {
  // TODO: Replace with autogenerated hook
  const {
    data: userProfileData,
    loading,
    error,
  } = useQuery(GetUserByIdWithProfile, {
    variables: {
      userId,
    },
  });

  return {
    userProfileData: userProfileData?.user?.user,
    loading,
    error,
  };
};

const Mention = (props: {
  mention: string;
  key: string;
  withPills?: boolean;
}): JSX.Element => {
  const { parseMention } = mentionUtils;
  const mention = parseMention(props.mention) as mentionUtils.Mention;

  const { displayText } = mention;

  const MentionComponent = MENTIONS[mention.modelType];

  if (MentionComponent) {
    return <MentionComponent {...props} mention={mention} />;
  }

  return <>{`@${displayText}`}</>;
};

const MENTIONS = {
  user: UserMention,
  workspace_contacts: WorkspaceContactMention,
};

export { Mention, UserMention };
