import { LOOM_URI, WATCH_LATER_PAGE } from '@js/constants/routes';

// eslint-disable-next-line no-restricted-imports
import { useMutation } from '@apollo/client';
import { useVideoPasswordContext } from '@js/common/video-password';
import {
  UiEvents,
  usePlayerFromContext,
  useVideoContext,
  useIsWatchLaterEnabled,
} from '@js/common/video-player';
import React, { useState, useEffect } from 'react';

import { Toast, Text, Link, Icon, Arrange } from '@loomhq/lens';
import { SvgCheckCircleFill } from '@loomhq/lens/icons/check-circle-fill';
import RemoveVideoFromWatchLaterList from '@js/common/watch-later/RemoveVideoFromWatchLaterList.graphql';

import AddVideoToWatchLaterList from './AddVideoToWatchLaterList.graphql';

const WATCH_LATER_LINK: string = LOOM_URI + WATCH_LATER_PAGE;

const useWatchLaterClickListener = (onToggle: (newValue: boolean) => void) => {
  const player = usePlayerFromContext();

  useEffect(() => {
    if (!player) {
      return;
    }

    player.on([UiEvents.toggleWatchLater], onToggle);

    return () => {
      player.off([UiEvents.toggleWatchLater], onToggle);
    };
    // TODO(next author): Please update this hook to fix dependency issue
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [player]);
};

const WatchLaterEmbedVideoHandler = (): React.ReactElement => {
  // TODO
  return <></>;
};

const WatchLaterShareVideoHandler = (): React.ReactElement => {
  const { video } = useVideoContext();
  const { password } = useVideoPasswordContext();

  const videoId = video?.id;
  const videoTitle = video?.title;
  const isOnWatchLaterList = video?.isOnWatchLaterList;

  const [isToastOpen, setIsToastOpen] = useState(false);

  // TODO: Replace with autogenerated hook
  const [addToWatchLaterList] = useMutation(AddVideoToWatchLaterList, {
    onCompleted: data => {
      const { addVideoToWatchLaterList: result } = data;

      if (result?.success) {
        setIsToastOpen(true);
      }
    },
    refetchQueries: ['GetUserWatchLaterListCount'],
  });

  // TODO: Replace with autogenerated hook
  const [removeFromWatchLaterList] = useMutation(
    RemoveVideoFromWatchLaterList,
    {
      onCompleted: data => {
        const { removeVideoFromWatchLaterList: result } = data;

        if (result?.success) {
          setIsToastOpen(true);
        }
      },
      refetchQueries: ['GetUserWatchLaterListCount'],
    }
  );

  const onToggle = (newValue: boolean) => {
    if (newValue) {
      addToWatchLaterList({
        variables: {
          videoId,
          minutesFromUTC: new Date().getTimezoneOffset(),
          password,
        },
      });
    } else {
      removeFromWatchLaterList({ variables: { videoId } });
    }
  };

  useWatchLaterClickListener(onToggle);

  return (
    <Toast isOpen={isToastOpen} onCloseClick={() => setIsToastOpen(false)}>
      <Arrange alignItems="start" gap="small">
        <Icon icon={<SvgCheckCircleFill />} color="bodyInverse" />
        <div>
          <Text fontWeight="book" isInline={true}>
            You’ve {isOnWatchLaterList ? ' added ' : ' removed '}
          </Text>
          <Text fontWeight="bold" isInline={true}>
            {videoTitle}
          </Text>
          <Text fontWeight="book" isInline={true}>
            {isOnWatchLaterList ? ' to ' : ' from'} your{' '}
          </Text>
          <Text fontWeight="bold" isInline={true}>
            <Link variant="neutral" href={WATCH_LATER_LINK}>
              watch list
            </Link>
          </Text>
          <Text fontWeight="book" isInline={true}>
            .
          </Text>
        </div>
      </Arrange>
    </Toast>
  );
};

export const WatchLaterHandler = ({
  inEmbed = false,
}: {
  inEmbed?: boolean;
}): React.ReactElement => {
  const isWatchLaterEnabled = useIsWatchLaterEnabled();

  if (!isWatchLaterEnabled) {
    return <></>;
  }

  return (
    <>
      {inEmbed ? (
        <WatchLaterEmbedVideoHandler />
      ) : (
        <WatchLaterShareVideoHandler />
      )}
    </>
  );
};
