// TODO: Replace with autogenerated hook

import { getGraphQLClient } from '@js/utilities/graphql';

import { GetCurrentUserSsrDocument } from '@loomhq/graphql-preload';

import { getMemoizedInvariantGetCurrentUserSsrQuery } from '../schema/invariantGetCurrentUserSsrQuery';
import { CurrentUserOrLoggedOut } from '../schema/types';

const invariantGetCurrentUserSsrQuery =
  getMemoizedInvariantGetCurrentUserSsrQuery();

/**
 * Gets the current user from the Apollo cache. Generally prefer selectFromCurrentUserCache over this because it handles errors gracefully.
 *
 * @deprecated Use specific hooks like 'useCurrentUser' or custom graphql queries instead. This exists as a legacy bridge to assist in migrating legacy redux actions and selectors.
 * @throws CurrentUserError if the current user was not loaded correctly
 * @returns The current user.
 */
export const getCurrentUserFromCache = (): CurrentUserOrLoggedOut => {
  const apolloClient = getGraphQLClient();
  const currentUser = apolloClient.readQuery({
    query: GetCurrentUserSsrDocument,
  });

  return invariantGetCurrentUserSsrQuery(currentUser);
};
